### ISSUE TITLE
数据删除建议

### ISSUE THREAD

**Issue by wivd** [go-admin-team/go-admin#126]
go-admin的数据操作模块使用的gorm，model中的数据模型都有DeletedAt字段，按照gorm的文档，当数据表中有deleted_at字段时，数据删除执行的是软删除，数据没有在数据库中删除。
建议一：基础数据表不包括deleted_at字典，删除数据时，直接删除
建议二：用户业务数据，代码生成的时候，可以指定使用那种数据删除方式，生成不同的代码数据

**Comment by wenjianzhang** [comment]
感谢您对go-admin的信任和支持，您提出的建议我们会在后续版本进行添加和优化，谢谢！
