### ISSUE TITLE
希望项目中增加富文本编辑器和Markdown 编辑器 的示例

### ISSUE THREAD

**Issue by haimait** [go-admin-team/go-admin#168]
希望项目中增加富文本编辑器和Markdown 编辑器 的示例,这个是后台管理系统中必备的编辑工具
以下是vue-element-admin官网推荐的两款编辑器,希望引入到项目里的示例中,
Tinymce编辑器 :+1: 
 https://panjiachen.github.io/vue-element-admin-site/zh/feature/component/rich-editor.html#tinymce
Markdown 编辑器 tui.editor 作为新的编辑器:
https://panjiachen.github.io/vue-element-admin-site/zh/feature/component/markdown-editor.html#props

**Comment by wenjianzhang** [comment]
感谢您的关注，Tinymce编辑器在表单生成器中已经添加组件了哦！
