### ISSUE TITLE
菜单加外链，跳转到系统 外面去了，应该嵌入到本系统 的tab中才对吧？

### ISSUE THREAD

**Issue by ssuhvs** [go-admin-team/go-admin#239]
菜单加外链，跳转到系统外面去了，应该嵌入到本系统 的tab中才对吧？
比如我内嵌了一个http://baidu.com .点击的时候，直接新打开了一个页面，我期望的是能在一个tab页的iframe中显示

**Comment by wenjianzhang** [comment]
您好，目前是不支持这样子操作的，我们后续会考虑您的建议，谢谢！
