### ISSUE TITLE
给你提几个建议

### ISSUE THREAD

**Issue by P-peng** [go-admin-team/go-admin#242]
1. 首选自动生成的模型层。不应该使用 *，严重影响了查询的性能。

2. 对于return.go的封装，PageOK方法，封装太死，不应该这样，可以考虑下我的方法
func PageMap(c *gin.Context, result interface{}, count int, pageIndex int, pageSize int, msg string, value map[string]interface{}) {}
这样封装大大提高扩展性

**Comment by lonely181** [comment]
赞同，里边的搜索封装太过了，用自动生成的代码，要改动很多。特别是is_delete, create_by等等，很多表都没有这些字段。然后几个interface限制了必须要实现这几个方法。比较啰嗦了。

**Comment by wenjianzhang** [comment]
感谢您的建议，后续会考虑这部分的优化或者调整。
