### ISSUE TITLE
V1.2.0模板文件路径有些问题

### ISSUE THREAD

**Issue by mCloud** [go-admin-team/go-admin#248]
https://github.com/go-admin-team/go-admin/blob/68c51fb48064731866353464ce46c37d898f6d14/app/admin/apis/tools/gen.go#L24

这个实际文件名称为:  apis.go.template

https://github.com/go-admin-team/go-admin/blob/68c51fb48064731866353464ce46c37d898f6d14/app/admin/apis/tools/gen.go#L32

这里实际路径应该为: "template/v3/dto.go.template"

**Comment by wenjianzhang** [comment]
谢谢您的建议，我们会尽快修复该问题！感谢对go-admin-team的支持！
