### ISSUE TITLE
win10 goland初始化db报错

### ISSUE THREAD

**Issue by andya1985** [go-admin-team/go-admin#257]
![image](https://user-images.githubusercontent.com/10007321/95940853-f5712d00-0e11-11eb-86a4-ce0c5ccd5628.png)

![image](https://user-images.githubusercontent.com/10007321/95940889-091c9380-0e12-11eb-8e54-f511fae5d9b4.png)

Error: unknown shorthand flag: 'c' in -c=config/settings.dev.yml

**Comment by wenjianzhang** [comment]
# 首次配置需要初始化数据库资源信息
./go-admin migrate -c config/settings.yml

readme.md 中 有描述的哦。
