### ISSUE TITLE
migrate 版本号排序有误

### ISSUE THREAD

**Issue by szaquila** [go-admin-team/go-admin#261]
/admin/cmd/migrate/migration/init.go的44行

func (e *Migration) Migrate() {
	versions := make([]int, 0)
	for k := range e.version {
		versions = append(versions, k)
	}
	// sort.IntsAreSorted(versions) <-- 错误，这个是检查是否已经排序的, 不是进行排序
	sort.Ints(versions)
	var err error

/admin/cmd/migrate/migration/version/1602644950000_migrate.go的38行
func _1602644950000Test(db *gorm.DB, version string) error {
	return db.Transaction(func(tx *gorm.DB) error {
		// err := db.Migrator().RenameColumn(&models.SysConfig{}, "config_id", "id") <-- 错误
		// if err != nil {
		// 	return err
		// }
		list2 := []models.CasbinRule{
			{PType: "p", V0: "admin", V1: "/api/v1/config", V2: "GET"},
		}
		err := tx.Create(list2).Error
...
		// return db.Create(&common.Migration{  <-- 错误，在事务中使用db会导致数据库锁定
		return tx.Create(&common.Migration{  
			Version: version,
		}).Error

**Comment by wenjianzhang** [comment]
这个问题是因为新初始化和老用户的一个问题，因为模型变更了，所以对单表的变更就不需要要了；
