### ISSUE TITLE
“roleKey”  v1.2.1版本很多前端代码没有带上 导致权限判断失败

### ISSUE THREAD

**Issue by martin-ly** [go-admin-team/go-admin#266]
// 查询参数
      queryParams: {
        pageIndex: 1,
        pageSize: 10,
        ipaddr: undefined,
        userName: undefined,
        roleKey: undefined,
        status: undefined
      }
前端代码 请求 未带上 “roleKey”
导致页面切换 出现权限认证不通过。既然casbin是通用的组件 逻辑上每个请求都带上roleKey或者在请求路由上做逻辑选择不判断。

permission.go ----中代码判断

 		//检查权限
		res, err := e.Enforce(v["rolekey"], c.Request.URL.Path, c.Request.Method)
		tools.HasError(err, "", 500)

**Comment by martin-ly** [comment]
前端代码如果有个设计思维导图什么的  
我查看bug就会更快些 
这样我还可以使劲帮的上一点忙呢

**Comment by martin-ly** [comment]
OK ？

**Comment by wenjianzhang** [comment]
?您是有什么问题吗？
