### ISSUE TITLE
数据库配置读取 并初始化GROM 会出现nil引用 导致服务coredump

### ISSUE THREAD

**Issue by martin-ly** [go-admin-team/go-admin#269]
配置改为sqlite后goadmin直接core了。
框架大概看懂了  基本的model想法还是很不错的
就是很多细节需要完善
日志类直接用zap不可以么 硬是要自己实现吗？
直接把精力付出在go-admin核心模型的实现上不是很好吗？
权限模型 和 部门组织的模型 可以组合在一个实现中 CASBIN是有这个功能的？不过go-admin的分级也是比较简单的使用
迭代的逻辑没看太明白 只是觉得go-admin想法很不错 与其他类似的框架有着概念模型的本质的不同 但是迭代的路径发展有点偏

**Comment by martin-ly** [comment]
我会持续关注go-admin  如果迭代的够快 就好了

**Comment by kikiyou** [comment]
@martin-ly  我刚提交了个pr ：https://github.com/go-admin-team/go-admin/pull/271  支持sqlite
运行方式： go-admin server -c config/settings.sqlite.yml
