### ISSUE TITLE
在线文档部分内容未更新

### ISSUE THREAD

**Issue by misakichan** [go-admin-team/go-admin#273]
http://mydearzwj.gitee.io/go-admin-site/guide/ide.html    页面下

`按照下图所示进行配置，注意：填写 Program arguments 为 init -c=config/settings.dev.yml，完成之后点击`\

目前版本应改为migrate -c=config/settings.dev.yml

**Comment by wenjianzhang** [comment]
收到，doc也可以直接提交pr的哦，谢谢您的支持和建议！
