### ISSUE TITLE
怎么实现多表操作

### ISSUE THREAD

**Issue by QTTQ** [go-admin-team/go-admin#276]
看教程都是生成的单表增删改查，那多表关联表如何实现

**Comment by martin-ly** [comment]
这个不是这个框架要解决的问题呢 或者需要自己写  或者高端的graphql的问题领域

**Comment by wenjianzhang** [comment]
> 看教程都是生成的单表增删改查，那多表关联表如何实现

go-admin 目前已经支持外键关系 表生成的操作；

可以参考下图

![image](https://user-images.githubusercontent.com/3890175/100520943-a3c30d00-31db-11eb-9505-532bef53efe9.png)

![image](https://user-images.githubusercontent.com/3890175/100520999-df5dd700-31db-11eb-9915-0a9236683f52.png)
