### ISSUE TITLE
启动时用热重启 会把错

### ISSUE THREAD

**Issue by QTTQ** [go-admin-team/go-admin#277]
building...
running...
欢迎使用 go-admin 1.2.1 可以使用 -h 查看命令
也可以参考 http://doc.zhangwj.com/go-admin-site/guide/ksks.html 里边的【启动】章节
Error: requires at least one arg
app\admin\models\menu.go has changed
building...
failed to remove D:\goadmin\dirname\go-admin\tmp\main.exe, error: remove D:\goadmin\dirname\go-admin\D:\goadmin\dirname\go-admin\tmp\main.exe: The filename, directory name, or volume label syntax is incorrect.

**Comment by wenjianzhang** [comment]
Error: requires at least one arg
启动四需要传入命令的
