### ISSUE TITLE
配置用户管理的接口权限必出错？

### ISSUE THREAD

**Issue by martin-ly** [go-admin-team/go-admin#278]
`package middleware

//权限检查中间件
func AuthCheckRole() gin.HandlerFunc {
	return func(c *gin.Context) {
		data, _ := c.Get(jwtauth.JwtPayloadKey)
		v := data.(jwtauth.MapClaims)
		e := mycasbin.Casbin()
		//检查权限
		res, err := e.Enforce(v["rolekey"], c.Request.URL.Path, c.Request.Method)
		tools.HasError(err, "", 500)

		if res {
			c.Next()
		} else {
			c.JSON(http.StatusOK, gin.H{
				"code": 403,
				"msg":  "对不起，您没有该接口访问权限，请联系管理员",
			})
			**logss := fmt.Sprintf("%s [permission-deny] %s %s %s \r\n",
				tools.GetCurrentTimeStr(),
				c.Request.Method,
				c.Request.URL.Path,
				v["rolekey"],
			)**
			fmt.Println(logss)
			c.Abort()
			return
		}
	}
}
`
------------------------------这里我添加了打印 出错的接口信息

![image](https://user-images.githubusercontent.com/1536579/96930936-17903c80-14ef-11eb-8ddd-32581f8fc780.png)

切换用户管理时候接口权限报错------用户 admin--------------
日志打印：
`2020/10/23 05:01:38 M:/src_code/src/go-admin/app/admin/models/sysuser.go:229
[0.969ms] [rows:1] SELECT count(1) FROM `sys_user` left join sys_dept on sys_dept.dept_id = sys_user.dept_id
2020-10-23 05:01:38 [INFO] GET /api/v1/sysUserList?pageIndex=1&pageSize=10 200      7.9948ms       127.0.0.1
**2020-10-23 05:01:38 [permission-deny] POST /api/v1/configKey admin**
`

查询数据库：
`mysql> select * from  sys_casbin_rule where v1 = "/api/v1/configKey" and v0="admin" and v2="POST";
+--------+-------+-------------------+------+------+------+------+
| p_type | v0    | v1                | v2   | v3   | v4   | v5   |
+--------+-------+-------------------+------+------+------+------+
| p      | admin | /api/v1/configKey | POST | NULL | NULL | NULL |`

说明数据库 有我插入的数据 这个权限是1.2.1这个版本里面 初始化时候没有的

但是切换界面到 “用户管理” 总是报错

**Comment by martin-ly** [comment]
![image](https://user-images.githubusercontent.com/1536579/96931511-ff6ced00-14ef-11eb-964f-d0990aab7429.png)

**Comment by martin-ly** [comment]
奇怪上传不了截图么？

**Comment by martin-ly** [comment]
也验证过 大小写的问题  http 请求的大小写问题 没有发现enforce这个接口验证出错的原因

**Comment by sailingchen** [comment]
首先这个报错是向  http://你的域名/api/v1/configKey   POST 时产生的错误, 原因大概可能是 /api/v1/configKey这个接口并没有添加到菜单中，并且接口没有授权访问。  

**解决：**
添加一个菜单，可以加在 "必开接口" 那里：
请求方式：POST
路由地址：/api/v1/configKey

然后在角色授权里，将刚才添加的勾选。

**Comment by martin-ly** [comment]
我查看源代码 前端传入的参数和CASBIN的URL鉴权的冲突
删除操作日志那个接口也是 
比如  casbin 配置的url  是不包括query的后缀的 前端传入请求的URL 包含了字符串数组 导致casbin鉴权不通过

**Comment by martin-ly** [comment]
给出证明
将数据库表sys_casbin_rule的admin有关记录全部删除
插入记录
`p	admin	/api/v1/*	   (GET)|(PUT)|(POST)|(DELETE)	`		
**再次测试所有的接口就正常 而界面依然报错 和原来一样见上面的报错**

**Comment by yimtcode** [comment]
@sailingchen 不能将master分支更新下，让我们直接可以跑过来不报错，刚开始看很多还不理解，还不知道怎么修复这个问题。

**Comment by wenjianzhang** [comment]
> @sailingchen 不能将master分支更新下，让我们直接可以跑过来不报错，刚开始看很多还不理解，还不知道怎么修复这个问题。

使用新的版本，admin角色可以解决这个问题，但是其他用户是需要分配接口权限的，具体可以https://space.bilibili.com/565616721/channel/detail?cid=125737 根据视频设置

**Comment by shengdoushi** [comment]
这个问题，是要更新后端， 还是前端解决？
