### ISSUE TITLE
删除操作日志权限出错导致删除不了

### ISSUE THREAD

**Issue by martin-ly** [go-admin-team/go-admin#279]
`2020/10/23 06:05:14 M:/src_code/src/go-admin/app/admin/models/operlog.go:77
2020-10-23 06:05:18 [permission-deny] DELETE /api/v1/operlog/236,235,234,233,232,231,230,229,228,227 admin
`
插入数据库权限记录
`
mysql> insert sys_casbin_rule(p_type,v0,v1,v2) value("p","admin","/api/v1/operlog/:id","DELETE");
mysql> select * from  sys_casbin_rule where v1 = "/api/v1/operlog" and v0="admin" and v2="DELETE";
`
`2020-10-23 06:12:09 [permission-deny] DELETE /api/v1/operlog/237,236,235,234,233,232,231,230,229,228 admin`

测试UI web 依然报错
估计是重构带来的一些权限判断逻辑和初始化的问题
现在的问题是 插入数据后 还是会出现权限出错

**Comment by martin-ly** [comment]
也有可能是请求的URL 格式判断和casbin的URL的规则不匹配

**Comment by martin-ly** [comment]
测试了下   接口URL的格式   casbin的权限配置和初始化 存在一些不匹配 
需要你们重新梳理下  前端访问的URI也是 不然测试还是会出现很多问题

**Comment by martin-ly** [comment]
![Uploading image.png…]()

**Comment by martin-ly** [comment]
![image](https://user-images.githubusercontent.com/1536579/97170919-7e4f7780-17c7-11eb-9a26-b88bc6e3da09.png)

**Comment by wenjianzhang** [comment]
感谢您的反馈，您可以将出错的URL提供一下，方便更快的定位和解决问题，谢谢您的支持！

**Comment by wenjianzhang** [comment]
该问题已经处理，请更新！
