### ISSUE TITLE
管理员无法访问用户管理

### ISSUE THREAD

**Issue by yuzhongrong** [go-admin-team/go-admin#280]
![image](https://user-images.githubusercontent.com/7382234/97067664-3c210d00-15f2-11eb-8b7e-351e09b78a65.png)

**Comment by zhuqiyun** [comment]
遇到同样的问题

**Comment by wenjianzhang** [comment]
> 遇到同样的问题

如何操作遇到这个问题呢？

**Comment by zhuqiyun** [comment]
拉下来原始工程，master分支 ，初始化完毕，进入就是这样了。

**Comment by Wangmaryruth** [comment]
遇到同样的问题

**Comment by wenjianzhang** [comment]
done
