### ISSUE TITLE
使用代码生成，接口报以下问题，请问如何解决~

### ISSUE THREAD

**Issue by arronf2e** [go-admin-team/go-admin#283]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15780058/97387436-f2496700-1910-11eb-850f-47000a59d9ef.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wenjianzhang** [comment]
数据库名称不要出现中横线
