### ISSUE TITLE
不管进入哪个页面照片中的请求都会重复发一次

### ISSUE THREAD

**Issue by Wangmaryruth** [go-admin-team/go-admin#286]
![image](https://user-images.githubusercontent.com/54444661/97876682-267cb780-1d57-11eb-9c53-d1d6f8fa9418.png)

**Comment by Wangmaryruth** [comment]
![image](https://user-images.githubusercontent.com/54444661/97878845-1ca88380-1d5a-11eb-83a7-0fe994120d3e.png)

**Comment by wenjianzhang** [comment]
您好，这个可以了解一下跨域请求。谢谢您的建议与支持！
