### ISSUE TITLE
Failed to generate documentation using swag init

### ISSUE THREAD

**Issue by lamontu** [go-admin-team/go-admin#289]
Can not generate documentation after adding a new model using Pagination.

**To Reproduce**
1. Added a model file under the folder app/admin/models 
2. Added the service file using dto.Pagination under app/admin/dto 
3. Added the router file under app/admin/router. 
4. Execute `swag init` in the root directory

**Expected behavior**
swag init succeeded

**Screenshots**
![image](https://user-images.githubusercontent.com/20261113/98424714-8b287100-20cd-11eb-8c04-97ead04037b0.png)

**Version**
go version go1.15.2 windows/amd64
swag version v1.6.9

**Comment by techbnu** [comment]
you will use app.Page

there is "go-admin/tools/app" model.go

**Comment by wenjianzhang** [comment]
已修复
