### ISSUE TITLE
[BUG反馈] 新增部门数据缺失dept_path

### ISSUE THREAD

**Issue by tanganyu1114** [go-admin-team/go-admin#291]
版本：v1.2.2
问题：系统管理--部门管理  页面新增部门，新增数据部分字段缺失，导致员工管理中，按部门筛选不能正确的显示
缺失字段如下图：
![image](https://user-images.githubusercontent.com/48984491/98636005-ec1ba780-2360-11eb-92ad-58e0c5202730.png)

**Comment by wenjianzhang** [comment]
> 版本：v1.2.2
> 问题：系统管理--部门管理 页面新增部门，新增数据部分字段缺失，导致员工管理中，按部门筛选不能正确的显示
> 缺失字段如下图：
> ![image](https://user-images.githubusercontent.com/48984491/98636005-ec1ba780-2360-11eb-92ad-58e0c5202730.png)

感谢您的反馈，会尽快修正并更新。

**Comment by wenjianzhang** [comment]
可以尝试在爱拓科技节点下边添加，是否能够正确添加path，目前系统只支持一个根结点

**Comment by tanganyu1114** [comment]
提交了这个bug的修复requests #343 ，原因是updates更新多组元素，map应该是map[string]interface{}{}不能是map[string]string ，然后这里是新增，只修改dept_path，所以我使用了update来替代

**Comment by wenjianzhang** [comment]
[#343 ] 已经修复
