### ISSUE TITLE
[BUG反馈] 新增用户角色权限不能修改，显示错误为超级管理员

### ISSUE THREAD

**Issue by tanganyu1114** [go-admin-team/go-admin#292]
版本：v1.2.2
问题：在角色管理页面新增角色，给予任意权限后，点击修改权限权限，一直在加载中，无法加载成功，如下图1，一旦点击修改系统管理员权限后，所有角色的修改页面都会变成系统管理员，无法修改权限，如下图2，但是实际权限还是之前创建时选择的，前端页面显示存在问题

图1：
![image](https://user-images.githubusercontent.com/48984491/98637808-ed020880-2363-11eb-8def-eaf498ee683e.png)

图2：
![image](https://user-images.githubusercontent.com/48984491/98637563-811fa000-2363-11eb-92b6-00ae53c6794e.png)

**Comment by chen866** [comment]
同不能修改角色权限

**Comment by wenjianzhang** [comment]
done
