### ISSUE TITLE
头像无法更换

### ISSUE THREAD

**Issue by zhuqiyun** [go-admin-team/go-admin#293]

**Comment by zhuqiyun** [comment]
> _No description provided._
无法更换系统logo

**Comment by cjyzwg** [comment]
是的，没法更换，因为提示where 语句缺少，models/system.go下29行改成下面这个 就可以了 orm.Eloquent.Table("sys_setting").Model(&update).Where("settings_id=?", 1).Updates(&s).Error

**Comment by zhuqiyun** [comment]
> 是的，没法更换，因为提示where 语句缺少，models/system.go下29行改成下面这个 就可以了 orm.Eloquent.Table("sys_setting").Model(&update).Where("settings_id=?", 1).Updates(&s).Error

谢谢
