### ISSUE TITLE
vscode debug报错__debug_bin: Access is denied. Process

### ISSUE THREAD

**Issue by 107295472** [go-admin-team/go-admin#294]
会一值报错，_debubin  不能访问

**Comment by 107295472** [comment]
could not remove D:\go\work\go-admin\__debug_bin: remove D:\go\work\go-admin\__debug_bin: Access is denied.

**Comment by 107295472** [comment]
`could not remove D:\go\work\go-admin\__debug_bin: remove D:\go\work\go-admin\__debug_bin: Access is denied.
Process exiting with code: 0
`

**Comment by 107295472** [comment]
*__debug_bin  加到忽略文件里也不行，把git全删了，还是这个错误

**Comment by ogios** [comment]
请问怎么解决的，我也遇到这个问题了

**Comment by 107295472** [comment]
没有了，不知道就好了
