### ISSUE TITLE
运行go-admin migrate后，提示未找到settings.ssl

### ISSUE THREAD

**Issue by zyxk** [go-admin-team/go-admin#295]
win10环境下，运行 go-admin migrate -c=config/settings.dev.yml

错误提示  warning config not found settings.ssl in the configuration

请问怎么解决，谢谢

`D:\go-admin>go-admin migrate -c=config/settings.dev.yml
start init
warning config not found settings.ssl in the configuration
2020-11-12 12:04:29  file=logger/setup.go:44 level=fatal request logger setup error: %s0x15664c0`

**Comment by cjyzwg** [comment]
在settings.dev.yml 加一句   ssl:enable: false 就可以了

**Comment by sootma** [comment]
按你的加了 ssl:enable: false, 还是报下面的
2020-11-15 17:21:56  file=logger/setup.go:44 level=fatal request logger setup error: %s0xa56900

我用的是postgresql

**Comment by Hujh-work** [comment]
> 按你的加了 ssl:enable: false, 还是报下面的
> 2020-11-15 17:21:56 file=logger/setup.go:44 level=fatal request logger setup error: %s0xa56900
> 
> 我用的是postgresql

楼主解决了吗？遇到了同样的问题。。

**Comment by sootma** [comment]
此项目可能主要是在mysql中运行的，对postgresql有几处明显的问题，最基本的驱动名称都写错了，这个我改了，可以提交合并过来。但生成数据表的数据类型，int(11),int(1)这种写法也是针对mysql的，在postgresql报错，你可以你在本地改错，就可以运行了。
另外，要手动setting.yml中的日志目录要改成系统 的类型，比如：d:/logs, 然后还要在此目录下手工加3个目录：bus, job, request.
再 build, 再 migrate， OK.

**Comment by zyxk** [comment]
用dev版本可以.
