### ISSUE TITLE
file=logger/setup.go:44 level=fatal request logger setup error: %s0x13a63e0

### ISSUE THREAD

**Issue by Hujh-work** [go-admin-team/go-admin#298]
下载的最新版，初始化数据库报错，新手求帮助。。。。setup.go文件如下：
package logger

import (
	"path/filepath"

	"github.com/go-admin-team/go-admin-core/debug/writer"
	"github.com/go-admin-team/go-admin-core/logger"

	"go-admin/common/log"
)

//func Setup() (*glog.Logger, *glog.Logger) {
//	var Logger *glog.Logger
//	var JobLogger *glog.Logger
//	var RequestLogger *glog.Logger
//
//	Logger = glog.New()
//	_ = Logger.SetPath(config.LoggerConfig.Path + "/bus")
//	Logger.SetStdoutPrint(config.LoggerConfig.EnabledBUS && config.LoggerConfig.Stdout)
//	Logger.SetFile("bus-{Ymd}.log")
//	_ = Logger.SetLevelStr(config.LoggerConfig.Level)
//
//	JobLogger = glog.New()
//	_ = JobLogger.SetPath(config.LoggerConfig.Path + "/job")
//	JobLogger.SetStdoutPrint(false)
//	JobLogger.SetFile("db-{Ymd}.log")
//	_ = JobLogger.SetLevelStr(config.LoggerConfig.Level)
//
//	RequestLogger = glog.New()
//	_ = RequestLogger.SetPath(config.LoggerConfig.Path + "/request")
//	RequestLogger.SetStdoutPrint(false)
//	RequestLogger.SetFile("access-{Ymd}.log")
//	_ = RequestLogger.SetLevelStr(config.LoggerConfig.Level)
//
//	Logger.Info(tools.Green("Logger init success!"))
//	return Logger, JobLogger
//}

// SetupLogger 日志
func SetupLogger(path string, subPath string) logger.Logger {
	var setLogger logger.Logger
	output, err := writer.NewFileWriter(filepath.Join(path, subPath), "log")
	if err != nil {
		log.Fatal("request logger setup error: %s", err.Error)
	}
	setLogger = logger.NewHelper(logger.NewLogger(logger.WithOutput(output)))
	return setLogger
}

**Comment by JaydonRan** [comment]
这个是一个路径问题，我把这个文件里写入绝对路径就成功了，但是我不知道要怎么从根本上去解决它
github.com/go-admin-team/go-admin-core/debug/writer/file.go
`
// NewFileWriter 实例化FileWriter
func NewFileWriter(path, suffix string) (*FileWriter, error) {
       //我修改了这里------------------------------------------------------
	//filename := filepath.Join(path, fmt.Sprintf("%s.%s", time.Now().Format(FileNameTimeFormat), suffix))
	var filename string
	filename = "E:\\work\\farm91\\go-admin\\temp\\logs\\bus\\2020-11-18.log"
       //--------------------------------------------------------------------
	fmt.Println(filename)
	file, err := os.OpenFile(filename, os.O_WRONLY|os.O_APPEND|os.O_CREATE|os.O_SYNC, 0600)
	fmt.Println(file)
	fmt.Println(err)
	if err != nil {
		return nil, err
	}
	return &FileWriter{
		path:   path,
		suffix: suffix,
		file:   file,
	}, nil
}

`

**Comment by JaydonRan** [comment]
1. 你在你的项目盘建好相应的文件夹，  比如 E:\temp\logs\bus  E:\temp\logs\job  E:\temp\logs\request。

2.修改配置文件
`
logger:
    # 日志存放路径
    #---------------修改这里    像这样 就可以了----------------------------
    path: E:\temp\logs
    # 控制台日志
    stdout: true
    # 日志等级
    level: all
    # 业务日志开关
    enabledbus: true
    # 请求日志开关
    enabledreq: false
`

**Comment by Hujh-work** [comment]
感谢！数据库初始化成功了

**Comment by Hujh-work** [comment]
已经解决了，非常感谢



在 2020-11-18 13:08:54，"JaydonRan" <notifications@github.com> 写道：

你在你的项目盘建好相应的文件夹， 比如 E:\temp\logs\bus E:\temp\logs\job E:\temp\logs\request。

2.修改配置文件
logger: # 日志存放路径 #---------------修改这里 像这样 就可以了---------------------------- path: E:\temp\logs # 控制台日志 stdout: true # 日志等级 level: all # 业务日志开关 enabledbus: true # 请求日志开关 enabledreq: false

**Comment by Hujh-work** [comment]
已经解决了，谢谢！
















在 2020-11-18 02:20:05，"JaydonRan" <notifications@github.com> 写道：

这个是一个路径问题，我把这个文件里写入绝对路径就成功了，但是我不知道要怎么从根本上去解决它
github.com/go-admin-team/go-admin-core/debug/writer/file.go
`
// NewFileWriter 实例化FileWriter
func NewFileWriter(path, suffix string) (*FileWriter, error) {
//我修改了这里------------------------------------------------------
//filename := filepath.Join(path, fmt.Sprintf("%s.%s", time.Now().Format(FileNameTimeFormat), suffix))
var filename string
filename = "E:\work\farm91\go-admin\temp\logs\bus\2020-11-18.log"
//--------------------------------------------------------------------
fmt.Println(filename)
file, err := os.OpenFile(filename, os.O_WRONLY|os.O_APPEND|os.O_CREATE|os.O_SYNC, 0600)
fmt.Println(file)
fmt.Println(err)
if err != nil {
return nil, err
}
return &FileWriter{
path: path,
suffix: suffix,
file: file,
}, nil
}

`

**Comment by jackluo2012** [comment]
![image](https://user-images.githubusercontent.com/2638586/99933333-b7164880-2d95-11eb-8ab7-691ca994f3b0.png)
同时要建立这么多文件jia

**Comment by wenjianzhang** [comment]
done
