### ISSUE TITLE
最新版代码生成后，后台编译不通过，pkg/logger/setup.go:4:2: cannot find package

### ISSUE THREAD

**Issue by Hujh-work** [go-admin-team/go-admin#303]
新手求帮助😔

**Comment by cys138138** [comment]
拉取最新代码或者手动建立  temp/logs/bus  temp/logs/job  temp/logs/request

**Comment by wenjianzhang** [comment]
该问题新版本已经修复，如果是老版本可以加一下logs目录，谢谢您的支持

> 新手求帮助😔

该问题新版本已经修复，如果是老版本可以加一下logs目录，谢谢您的支持
