### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by Hujh-work** [go-admin-team/go-admin#306]
代码生成后，后台重新编译了，前段报错404.。。。

**Comment by cys138138** [comment]
ui 重新拉取 重新run

**Comment by wenjianzhang** [comment]
> 代码生成后，后台重新编译了，前段报错404.。。。

谢谢您的反馈；
为了更好的帮助您，首先需要确认几个问题：
1、前后台编译是否报错；
2、是否对配置进行修改；
3、可以将出错的画面贴出来，方便更好的描述您的问题。

**Comment by Hujh-work** [comment]
已经解决，谢谢







在 2020-11-28 23:53:27，"wenjianzhang" <notifications@github.com> 写道：

代码生成后，后台重新编译了，前段报错404.。。。

谢谢您的反馈；
为了更好的帮助您，首先需要确认几个问题：
1、前后台编译是否报错；
2、是否对配置进行修改；
3、可以将出错的画面贴出来，方便更好的描述您的问题。
