### ISSUE TITLE
就这样一个大量注释代码，命名逻辑混乱的项目，整个还一半成品，能拿到3k star？

### ISSUE THREAD

**Issue by chaseSpace** [go-admin-team/go-admin#308]
我还要基于这二次开发，我真的。。。

**Comment by chaseSpace** [comment]
有疑问的直接去看代码，我说都懒得说了

**Comment by chaseSpace** [comment]
大量注释代码
随意使用反引号``（随处都是。。）
随处无意义注释
函数返回err却不处理（随处。。）
可能出现err的地方却忽略
不匹配逻辑的变量命名（e.g. api/cmd/server.go AppRouters）
不严谨的逻辑（e.g. api/cmd/server.go run()开头设置gin mode这里，ginmode还受到环境变量GIN_MODE影响）
莫名其妙的逻辑（e.g. api/cmd/server.go run() engine变量创建）
全局对象已经初始化，却在启动时再次赋值(e.g. common/global/adm.go.Logger)
混乱的目录结构（e.g. tools/utils.go pkg/utils.go）
混乱的目录结构2（e.g. 既然有了cmd/，就应该把main.go放在cmd/，cmd_ctl和main.go可以同时放在cmd/下并不冲突）

**Comment by wenjianzhang** [comment]
谢谢您的提交的建议！

**Comment by chaseSpace** [comment]
### 提高这个项目的代码质量应该作为你们下一步的开发计划。
我看过那么多开源项目，这个项目的代码质量和star是最不匹配的，我也不说那么多，既然你们在持续维护，不是毕业生项目，你们就应该注意一下，虽然你这个不是pkg项目，也不应该提交这样不规范的像草稿一样的代码。我看了很多issue，几乎都是很新手在提问，所以你们的项目的质量才提不上去啊。

**Comment by MeDeity** [comment]
我挺喜欢这套系统的UI和交互 感谢作者
