### ISSUE TITLE
我生成的代码,查询语句中被强行加了一个  `deleted_at` IS NULL 

### ISSUE THREAD

**Issue by ssuhvs** [go-admin-team/go-admin#310]
我搜了一遍代码没找到呢
我生成的代码,查询语句中被强行加了一个  `deleted_at` IS NULL 

请问是在哪里控制 的？ 没找到在哪里去掉

**Comment by wenjianzhang** [comment]
> 我搜了一遍代码没找到呢
> 我生成的代码,查询语句中被强行加了一个 `deleted_at` IS NULL
> 
> 请问是在哪里控制 的？ 没找到在哪里去掉

go-admin 默认使用的gorm 软删除 所以需要 `deleted_at`

如果需要调整可以在modles 中对应的文件进行修改 `gorm.Model`

**Comment by ArrowJustDoIt** [comment]
可以加一个Unscoped()

**Comment by wenjianzhang** [comment]
系统整体使用的是软删除，可根据自己不同的业务进行个别调整，对系统无影响
