### ISSUE TITLE
actions 更新空值处理

### ISSUE THREAD

**Issue by szaquila** [go-admin-team/go-admin#318]
admin/common/actions/update.go
44行调整
		sel := Select(req)
		if len(sel) == 0 {
			db = db.WithContext(c).Scopes(
				Permission(object.TableName(), p),
			).Where(req.GetId()).Updates(object)
		} else {
			db = db.WithContext(c).Scopes(
				Permission(object.TableName(), p),
			).Select(sel).Where(req.GetId()).Updates(object)
		}
最后增加
func Select(input interface{}) []string {
	fc := reflect.ValueOf(input).MethodByName("Select")
	if fc.IsValid() {
		out := fc.Call(nil)
		return out[0].Interface().([]string)
	}
	return []string{}
}

# ---------------------------------------------------------
在需要录入空值的模块的dto文件中增加需要更新的列
func (s *HostControl) Select() []string {
	return []string{"name", "description", "is_active"}
}

**Comment by lwnmengjing** [comment]
建议非常好，谢谢，
如果actions后端复杂化的情况下，肯定要加上的
