### ISSUE TITLE
请支持主键名称不是id的表的代码生成

### ISSUE THREAD

**Issue by zaster** [go-admin-team/go-admin#321]
编译时会报主键字段未定义的错误
app/admin/models/crnwaytype.go:26:10: e.TYPEID undefined (type *CrnWayType has no field or method TYPEID)

**Comment by wenjianzhang** [comment]
主键目前只支持id，另外还有一些必须按字段

**Comment by Jamiory** [comment]
支持联合主键吗，目前是否只支持主键是id字段的表？
