### ISSUE TITLE
角色必开接口已开，请求 api/v1/configKey 仍提示：对不起，您没有该接口访问权限，请联系管理员

### ISSUE THREAD

**Issue by luckylsx** [go-admin-team/go-admin#331]

**Comment by shengdoushi** [comment]
我也遇到这个问题， 现在我都是放出超级管理员给用户用

**Comment by wenjianzhang** [comment]
新版本一修改这个问题

**Comment by shengdoushi** [comment]
楼主试试在接口权限中除了 “必开接口”外， 再选上“角色管理”下的“获取角色菜单”

**Comment by luckylsx** [comment]
> 楼主试试在接口权限中除了 “必开接口”外， 再选上“角色管理”下的“获取角色菜单”
暂时做 了个修改，admin 账号认为超级管理员，非admin 账号，不调该接口

**Comment by luckylsx** [comment]
> 新版本修改这个问题
你好，这个bug 有人修吗？如果没人关注的话，我准备修复下

**Comment by wenjianzhang** [comment]
这个问题已经修复了，请更新最新版本使用。
