### ISSUE TITLE
角色管理->修改角色，菜单权限一直加载中

### ISSUE THREAD

**Issue by yimtcode** [go-admin-team/go-admin#334]
环境：
v1.2.2
问题：
1. 角色管理->修改角色，菜单权限一直加载中。
2. 角色管理->修改角色，权限字符是可以随便给的吗，只要不是已存在的？
<img width="507" alt="图片" src="https://user-images.githubusercontent.com/33422693/103118132-7bc6ac80-46a8-11eb-85e1-20c74e51f4ee.png">

**Comment by wenjianzhang** [comment]
新版本已经修复该问题。

**Comment by pengfawen** [comment]
新版本预计什么时间发布？
