### ISSUE TITLE
添加菜单的时候，显示添加完成，但是右边的菜单没有显示出来，

### ISSUE THREAD

**Issue by wangmingche** [go-admin-team/go-admin#336]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
看了代码是没有添加关联表sys_role_menu 权限表

**Comment by wenjianzhang** [comment]
请问，当前使用的是哪个版本？

**Comment by wenjianzhang** [comment]
左侧菜单没有出来吗？是自动生成的菜单数据还是那里操作的呢？
