### ISSUE TITLE
后端返回错误时，code也是200，但是前台直接判断200就当做成功了

### ISSUE THREAD

**Issue by itltf512116** [go-admin-team/go-admin#338]
**Describe the bug**
后端处理请求入库时如果返回失败，返回的是code=200,和一个错误

**To Reproduce**
1. 前端：系统工具--》系统配置--》保持
2. 服务端日志打印[rows:0] UPDATE `sys_setting` ...
3. 前端得到的响应是：{"code":200,"data":null,"msg":"WHERE conditions required","requestId":"5481be47-cd8f-43e1-b23c-d3c5698157a4"}
4. axios处理逻辑中判断当做成功处理，导致将系统设置缓存时失败：commit('SET_INFO', data) //data此时是null

**Desktop (please complete the following information):**
 - Version [go-admin 1.2.0 ]

**Comment by itltf512116** [comment]
sys_setting表在当前逻辑中应该只有一行语句，如果是这样的话，那这块的更新功能应该调用gorm的save方法直接更新所有字段，否则在调用update方法时应该传递条件，[Update](https://gorm.io/zh_CN/docs/update.html)，不传条件就会返回错误：ErrMissingWhereClause，提示上面的“WHERE conditions required”

**Comment by wenjianzhang** [comment]
update 默认是使用id进行更新的
