### ISSUE TITLE
miss file template/

### ISSUE THREAD

**Issue by itltf512116** [go-admin-team/go-admin#339]
**Describe the bug**
好像缺少文件：go-admin/app/admin/apis/tools/gen.go：
template/v3/no_actions/api.go.template
template/v3/no_actions/dto.go.template

**Desktop (please complete the following information):**
 - Version [1.2.0]

**Comment by wenjianzhang** [comment]
谢谢您的提交的问题，可以将1.2.2版本中的对应文件下载使用即可
