### ISSUE TITLE
 dev 系统配置图片上传有问题,第三方上传代码没有走

### ISSUE THREAD

**Issue by haimait** [go-admin-team/go-admin#349]
dev 系统配置图片上传有问题,第三方上传代码没有走

**Comment by wenjianzhang** [comment]
好的这个问题，谢谢！将在下一个版本进行修复。

**Comment by gitzwt** [comment]
source判断逻辑修复下,目前是本地存储了,然后还继续往oss上传,加个设置默认本地服务器存储,把oss的配置也加入config的settings文件里吧

**Comment by wenjianzhang** [comment]
done
