### ISSUE TITLE
字典报错

### ISSUE THREAD

**Issue by haimait** [go-admin-team/go-admin#354]
2021/02/21 04:02:07 /media/haima/34E401CC64DD0E28/site/go/src/fofa2/go-admin/app/admin/service/sys_dict_data.go:124 sql: Scan error on column index 11, name "update_by": converting driver.Value type []uint8 ("") to a int: invalid syntax; sql: Scan error on column index 11, name "update_by": converting driver.Value type []uint8 ("") to a int: invalid syntax

**Comment by wenjianzhang** [comment]
可以将sys_dict_data表中的update_by空值设置为0
