### ISSUE TITLE
文件管理文件上传报错

### ISSUE THREAD

**Issue by haimait** [go-admin-team/go-admin#358]
文件管理文件上传报错

**Comment by haimait** [comment]
{"requestId":"5f4e1eef-5c6c-4aac-8e8b-09601ea873b3","code":200,"msg":"上传第三方失败","data":null}{"requestId":"1d2e2d66-6691-4f43-a773-67c54d1081dc","code":200,"msg":"上传成功","data":null}

**Comment by wenjianzhang** [comment]
修改一下上传的oss信息就好了

**Comment by wenjianzhang** [comment]
done
