### ISSUE TITLE
api/v1/dict/typelist这个接口加上DictName参数就访问报错

### ISSUE THREAD

**Issue by D2GO** [go-admin-team/go-admin#366]
api/v1/dict/typelist?DictName=abc就会报502错误
我在本地部署的版本发现有此问题，
在线演示demo也存在此问题。（http://www.zhangwj.com/#/upms/dict）

**Comment by lwnmengjing** [comment]
目前版本有重大升级，后续会持续跟进这个问题

**Comment by wenjianzhang** [comment]
最新版本已经修复
