### ISSUE TITLE
Migrate Version排序bug

### ISSUE THREAD

**Issue by harrywangaa** [go-admin-team/go-admin#383]
func (e *Migration) Migrate() {
         ...
	sort.IntsAreSorted(versions)
         ...
}

语法更换成 --> sort.Ints(versions)

**Comment by wenjianzhang** [comment]
![image](https://user-images.githubusercontent.com/3890175/113128387-54095680-924c-11eb-914e-b68d04b60d63.png)
有什么问题吗？

**Comment by harrywangaa** [comment]
![image](https://user-images.githubusercontent.com/39321927/113277373-39e67b80-9313-11eb-95a5-e129f3621fc9.png)

奇怪我down下来的代码只有一行， 我重新更新下， 可能是之前自己改掉了。
