### ISSUE TITLE
模型驼峰体问题

### ISSUE THREAD

**Issue by G-Akiraka** [go-admin-team/go-admin#392]
第一种方法正常，前大写后全部小写
Authkey string `json:"authkey" gorm:"type:varchar(255);comment:秘钥"`

下面这种前端无法获取到该数据
AuthKey string `json:"authKey" gorm:"type:varchar(255);comment:秘钥"`
获取如下,可以看到authKey就获取不到内容了
{id: 1, name: "xxx", authKey: "", status: "2", remark: "", createdAt: "2021-04-09T22:03:35.743+08:00",…}

**Comment by wenjianzhang** [comment]
首先确认一下数据库字段名称 auth_key 蛇形结构可以正常转化的哦

**Comment by closetool** [comment]
@G-Akiraka @wenjianzhang 可能是gorm 1.21版本的问题, 这个版本bug很多, 建议使用1.20
