### ISSUE TITLE
代码生成设置和实际结果不一样

### ISSUE THREAD

**Issue by JuchangGit** [go-admin-team/go-admin#399]
![image](https://user-images.githubusercontent.com/34911052/114837687-9020e780-9e06-11eb-9e48-95885c97ddb7.png)
![image](https://user-images.githubusercontent.com/34911052/114837707-944d0500-9e06-11eb-8e44-327ca7f6629f.png)
代码生成工具bug

**Comment by wenjianzhang** [comment]
目前新建和编辑使用的是一个form,编辑是无效的
