### ISSUE TITLE
刷新token的函数客户端以及服务端不一致

### ISSUE THREAD

**Issue by xingyuejun** [go-admin-team/go-admin#402]
服务器
	r.GET("/refresh_token", authMiddleware.RefreshHandler)

客户端
export function refreshtoken(data) {
  return request({
    url: '/refreshtoken',
    method: 'post',
    data
  })
}

**Comment by wenjianzhang** [comment]
客户端目前没有对token进行刷新的功能，有需要可以微调代码就能支持😊
