### ISSUE TITLE
生成代码与自带代码数据保存问题

### ISSUE THREAD

**Issue by G-Akiraka** [go-admin-team/go-admin#404]
1、比如编辑用户编辑默认用户，在备注里面添加 abcd，点击保存，数据可以正常保存，如果删除abc也正常，如果全部删除，数据无法保存，生成出来代码全部有这些问题包括系统自带问题，只能修改 service 找到对应内容，代码修改如下。
2、如果是bool类型数据前端传递true，当改为false时，前端提交ok，后端不会做处理，解决方法一致

```bash
# 原来
Where(c.GetId()).Updates(c)
# 改为
Where(c.GetId()).Updates(c).Save(c)
```

**Comment by wenjianzhang** [comment]
done
