### ISSUE TITLE
go-admin启动服务($ ./go-admin server)时，报"panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by stonecity** [go-admin-team/go-admin#406]
2021-04-29T16:20:16.682+0800  file: gorm@v1.21.6/callbacks.go:127 level: trace D:/Program Files/Golearn/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1-0.20210310135230-1608cc35b95b/adapter.go:362  [0.889ms] [rows:1] SELECT * FROM `sys_casbin_rule`
 2021-04-29T16:20:16.683+0800  file: gorm@v1.21.6/callbacks.go:127 level: trace D:/Program Files/Golearn/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1-0.20210310135230-1608cc35b95b/adapter.go:362  [0.516ms] [rows:1] SELECT * FROM `sys_casbin_rule`
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xe2769d]

goroutine 1 [running]:
github.com/go-admin-team/go-admin-core/sdk/config.Queue.Setup(0x0, 0x0, 0xc0004477c0, 0x2cbc6f8, 0xc0004477c0, 0x0)
        D:/Program Files/Golearn/pkg/mod/github.com/go-admin-team/go-admin-core/sdk@v1.3.5-rc.0/config/queue.go:47 +0x1fd
go-admin/cmd/api.setup()
        D:/Product/mile/Project/go-admin/cmd/api/server.go:79 +0x269
go-admin/cmd/api.glob..func1(0x274b2c0, 0x3455f70, 0x0, 0x0)
        D:/Product/mile/Project/go-admin/cmd/api/server.go:37 +0x27
github.com/spf13/cobra.(*Command).execute(0x274b2c0, 0x3455f70, 0x0, 0x0, 0x274b2c0, 0x3455f70)
        D:/Program Files/Golearn/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:835 +0x4ef
github.com/spf13/cobra.(*Command).ExecuteC(0x274b020, 0x131f6b0, 0x0, 0x1)
        D:/Program Files/Golearn/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        D:/Program Files/Golearn/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
go-admin/cmd.Execute()
        D:/Product/mile/Project/go-admin/cmd/cobra.go:52 +0x34
main.main()
        D:/Product/mile/Project/go-admin/main.go:20 +0x27

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
@stonecity plz run it with gorm 1.20.x

**Comment by iwalben** [comment]
the same error

2021-04-30T14:12:53.571+0800  file: gorm@v1.21.6/callbacks.go:127 level: trace /Users/guobangbang/go/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1-0.20210310135230-1608cc35b95b/adapter.go:362  [0.410ms] [rows:1] SELECT * FROM `sys_casbin_rule`
 2021-04-30T14:12:53.572+0800  file: gorm@v1.21.6/callbacks.go:127 level: trace /Users/guobangbang/go/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1-0.20210310135230-1608cc35b95b/adapter.go:362  [0.562ms] [rows:1] SELECT * FROM `sys_casbin_rule`
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x47b4d3d]

**Comment by hsluoyz** [comment]
@closetool why does it happen? Can we just lock dependency to v1.20.x?

**Comment by iwalben** [comment]
> @closetool why does it happen? Can we just lock dependency to v1.20.x?

i have the same error with you

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
@hsluoyz https://github.com/golang/go/wiki/Modules#version-selection
for they import gorm 1.21.x and go mod would choose higher version, instead of the version defined in gorm-adapter go.mod file

**Comment by hsluoyz** [comment]
@closetool this repo still uses Gorm v1.21.6:

https://github.com/go-admin-team/go-admin/blob/bf7934c20af9a45be989a4ea9905099380554468/go.mod#L30

Based on our previous issue: https://github.com/casbin/gorm-adapter/issues/98#issuecomment-825492311 

```
Thanks @hsluoyz Works fine with 1.20.x and as well with the latest 1.21.8
```

Can we upgrade the Gorm version in this repo to latest 1.21.8 to fix this issue? If yes, plz make a PR.

**Comment by hsluoyz** [comment]
@closetool plz make PR to update go-admin to use Gorm adapter v3.2.12: https://github.com/casbin/gorm-adapter/pull/107#issuecomment-830576044

**Comment by closetool** [comment]
@hsluoyz go-admin does not import gorm-adapter in go.mod
https://github.com/go-admin-team/go-admin/blob/master/go.mod

**Comment by hsluoyz** [comment]
@closetool I think it uses this https://github.com/go-admin-team/gorm-adapter ?

**Comment by wenjianzhang** [comment]
```yml
queue:
    memory:
      poolSize: 100
```

append in config file
