### ISSUE TITLE
生成模版的几个小bug

### ISSUE THREAD

**Issue by l0n3rs** [go-admin-team/go-admin#408]
首先是time包
![image](https://user-images.githubusercontent.com/31120718/116988164-9669fb80-ad02-11eb-9994-e949d7d11906.png)
这种只需要进对应go文件加上time包
而这个s需要进到代码把s改成m，我这边是这样ok的，具体如何没跟过去看

**Comment by wenjianzhang** [comment]
这个是生成工具的问题吗？

**Comment by l0n3rs** [comment]
是的，生成出来的有问题，最开始的原始代码没问题

**Comment by wenjianzhang** [comment]
done
