### ISSUE TITLE
cmd/migration/models里的数据库定义 和  app/admin/models 下的定义，是否存在维护代码隐患？

### ISSUE THREAD

**Issue by chenkaiC4** [go-admin-team/go-admin#414]
如题，这种设计是否会导致加大项目后期维护成本？

**Comment by wenjianzhang** [comment]
这两处模型的作用是不一样的，migrate中的model 是为了记录模型的变更，数据库还原使用的，app中的model是业务中怎删改查使用的；业务中添加字段可能比较常见，但是数据库还原同样也是需要的哦
