### ISSUE TITLE
最新版本，无法使用代码生成功能

### ISSUE THREAD

**Issue by chenkaiC4** [go-admin-team/go-admin#415]
查了源码，原因有二：
1. registerSysTableRouter，这个路由没有加入auth验证，导致jwt信息里，没有用户的id（identify），进而导致 genTableInit函数里的需要的createBy字段是空的。
2. genTableInit里缺乏UpdateBy的定义，数据库操作失败。

几个希望作者忙里偷闲回复下的问题：
1. 作者是否考虑逐步引入测试机制？感觉这样的代码问题是比较低级的，有测试检测时，基本是不可能发布的。
2. 文档。特别是各个feature的设计思路，不管是使用还是想帮忙修复bug，有了设计思路，大家都能更快的定位问题，而不是从代码里捕捉蛛丝马迹，去修复问题（不是不可以，但是效率不高）。
3. 能够有一个roadmap，当前有多少已知问题，未来的规划，需要大家帮助什么，都可以放上去。

希望作者考虑下上面几个问题。

**Comment by wenjianzhang** [comment]
问题一&二、gen代码正常来说只能本地使用，所以没有添加用户认证设置默认值即可；

文档：https://doc.go-admin.dev 也希望您的pr
