### ISSUE TITLE
我想咨询下 我想写前端api比如 小程序的接口 是怎么样的入口形式写呢 ？

### ISSUE THREAD

**Issue by jetBn** [go-admin-team/go-admin#425]

**Comment by jetBn** [comment]
那就是说现在只能写后端的吗 ？ 比如我要写app 小程序这样的api是都得自己重新构建目录写 ？

**Comment by jetBn** [comment]
能否可以把model提取到公共部分 供 前端api 使用？

**Comment by wenjianzhang** [comment]
> 能否可以把model提取到公共部分 供 前端api 使用？

可以，但不建议这么使用

**Comment by jetBn** [comment]
> > 能否可以把model提取到公共部分 供 前端api 使用？
> 
> 可以，但不建议这么使用

那我写前端api 重新建model？

**Comment by wenjianzhang** [comment]
> > > 能否可以把model提取到公共部分 供 前端api 使用？
> > 
> > 
> > 可以，但不建议这么使用
> 
> 那我写前端api 重新建model？

正常情况下是需要重新创建的
