### ISSUE TITLE
定时任务，触发函数，无法正常关闭

### ISSUE THREAD

**Issue by xiaoChannel** [go-admin-team/go-admin#432]
![image](https://user-images.githubusercontent.com/18231098/120102482-d4313700-c17d-11eb-80a9-d6edb52a868f.png)
![image](https://user-images.githubusercontent.com/18231098/120102494-e27f5300-c17d-11eb-89c4-70e768ccf928.png)
且日志逻辑一直在跑，状态也未改变
![image](https://user-images.githubusercontent.com/18231098/120102500-edd27e80-c17d-11eb-8602-a94ec79c7021.png)

**Comment by wenjianzhang** [comment]
done
