### ISSUE TITLE
如何修改项目名

### ISSUE THREAD

**Issue by rhd-dream** [go-admin-team/go-admin#435]
使用该框架进行开发，需要将go-admin名称换成对应的项目名，如何进行更换？直接修改项目名好像会导致依赖出错

**Comment by wenjianzhang** [comment]
> 使用该框架进行开发，需要将go-admin名称换成对应的项目名，如何进行更换？直接修改项目名好像会导致依赖出错



> 用该框架进行开发，需要将go-admin名称换成对应的项目名，如何进行更换？直接修改项目名好像会导致依赖出错
> 可以全局搜索 "go-admin/ 尝试进行替换

以上操作是否可以解决你的问题？
