### ISSUE TITLE
配置文件 加入 Redis 缓存 无效

### ISSUE THREAD

**Issue by allenLew1991** [go-admin-team/go-admin#441]
![image](https://user-images.githubusercontent.com/3362015/120650136-0d381700-c4b0-11eb-8e2e-bd0bf8c6b96f.png)

yml配置文件中加入cache配置项

执行 ./go-admin config -c config/settings.yml
发现 缓存配置无效

![image](https://user-images.githubusercontent.com/3362015/120649977-ec6fc180-c4af-11eb-874f-b348759187f9.png)
@wenjianzhang

**Comment by wenjianzhang** [comment]
cache:
    redis:
      addr: 127.0.0.1:6379
      password: xxxxxx
      db: 2
