### ISSUE TITLE
教程api有点老

### ISSUE THREAD

**Issue by sszyc8** [go-admin-team/go-admin#442]
![82FC4B34-AC1C-44B0-B389-B30361054532](https://user-images.githubusercontent.com/6659558/121454981-4ef81e80-c9d6-11eb-959f-66c9263879bc.png)
这块文档有点老

**Comment by wenjianzhang** [comment]
谢谢指出，也希望大家能够提交pr

**Comment by wenjianzhang** [comment]
已经更新 https://doc.go-admin.dev/guide/intro/tutorial01.html#%E7%BC%96%E5%86%99%E7%AC%AC%E4%B8%80%E4%B8%AA%E6%8E%A5%E5%8F%A3
