### ISSUE TITLE
go mod tidy 歧义导入

### ISSUE THREAD

**Issue by godhelpjun** [go-admin-team/go-admin#444]
清除go.mod,运行go mod tidy,报错如下
go: finding module for package github.com/alibaba/sentinel-golang/adapter/gin
go-admin/app/admin/apis/monitor imports
        github.com/go-admin-team/go-admin-core/sdk/pkg: ambiguous import: found package github.com/go-admin-team/go-admin-core/sdk/pkg in multiple modules:
        github.com/go-admin-team/go-admin-core v1.3.4 (C:\Users\Administrator\go\pkg\mod\github.com\go-admin-team\go-admin-core@v1.3.4\sdk\pkg)
        github.com/go-admin-team/go-admin-core/sdk v1.3.0 (C:\Users\Administrator\go\pkg\mod\github.com\go-admin-team\go-admin-core\sdk@v1.3.0\pkg)

**Comment by wenjianzhang** [comment]
使用的是go-admin哪个版本

**Comment by godhelpjun** [comment]
git clone 最新版本

**Comment by wenjianzhang** [comment]
版本已经更新
