### ISSUE TITLE
sqlite编译经常出问题,那么支持sqlite的意义是啥

### ISSUE THREAD

**Issue by godhelpjun** [go-admin-team/go-admin#446]
讲真的,几个人web开发用sqlite?主要是经常go build 编译出错,可以留在文档里,真的需要的人 自己去看来整就好了 没必要每个人都需要来整一遍sqlite编译出错的问题吧
甚至可以判断下操作系统 不是linux类系统 默认不开启 不就完了

**Comment by ssuhvs** [comment]
你可以去用Java开发，几乎找不到sqlite 框架。 用go开发的很多是嵌入式，不懂不要瞎BB

**Comment by godhelpjun** [comment]
所以 这个go-admin原来是主要是运行在嵌入式设备上的web服务,学到了 感谢

**Comment by wenjianzhang** [comment]
> 讲真的,几个人web开发用sqlite?主要是经常go build 编译出错,可以留在文档里,真的需要的人 自己去看来整就好了 没必要每个人都需要来整一遍sqlite编译出错的问题吧
> 甚至可以判断下操作系统 不是linux类系统 默认不开启 不就完了

cgo 问题可以看看文档的解决办法 https://doc.go-admin.dev/guide/other/faq.html#_5-github-com-mattn-go-sqlite3-cgo-exec-gcc
