### ISSUE TITLE
为什么要移除内容管理、资源管理？ 

### ISSUE THREAD

**Issue by goople8** [go-admin-team/go-admin#456]
为什么要移除内容管理、资源管理？ 难道有这个功能不好？

**Comment by jason-wj** [comment]
我也想问，这个简易版的内容管理很好用，可以用来发布用户协议、使用协议、发布公告等

**Comment by wenjianzhang** [comment]
这两个功能偏业务了，如果需要再上一个版本还有保留可以继续使用。go-admin还是需要回归更基础。谢谢大家的支持！

**Comment by goople8** [comment]
也是醉了！！ 你能力不够，没那么多精力，可以不去更新它，但真不建议你删出它，你这样做会成功劝退一波用户。有那些功能恰恰是可以让用户可以直观的体验你的程序系统。为什么人家盖房子都要搞个样板间呢？ 你仔细品！！
再则你这搞得用之前版本的人，要来个git pull也不敢动，一动就会把相关模块删除了，人家还得多费事做整合！

**Comment by wenjianzhang** [comment]
> 也是醉了！！ 你能力不够，没那么多精力，可以不去更新它，但真不建议你删出它，你这样做会成功劝退一波用户。有那些功能恰恰是可以让用户可以直观的体验你的程序系统。为什么人家盖房子都要搞个样板间呢？ 你仔细品！！
> 再则你这搞得用之前版本的人，要来个git pull也不敢动，一动就会把相关模块删除了，人家还得多费事做整合！

1.3.x版本中仍然有这些功能，2.0.0版本及以后不在记入系统主要功能；

**Comment by jason-wj** [comment]
> 这两个功能偏业务了，如果需要再上一个版本还有保留可以继续使用。go-admin还是需要回归更基础。谢谢大家的支持！

谢谢，理解作者。
主框架还是得尽可能保持基础通用性，后期打包也能尽可能小一些。
偏个性化业务的功能，建议作者能留个入口和规则，方便使用者能以插件化的形式兼容到基础框架，可以参考下jeesite的框架思想。这样一来，后续使用者也能根据需要重新将内容管理和资源管理加入进来，并且不影响现有框架。

**Comment by wenjianzhang** [comment]
> jeesite

非常感谢您的建议，这个是go-admin未来的一个方向
