### ISSUE TITLE
go-admin 2.0.0-beta.6 bug

### ISSUE THREAD

**Issue by wivd** [go-admin-team/go-admin#457]
问题一:
go-admin 2.0.0-beta.6 新版本和新数据库，在数据初始化的时候，导入db.sql文件的时候报错，导致user等表没有数据，原因是db.sql中字段顺序和表结果不一样，导致无法导入数据
问题二：
代码生成bug，go-admin 2.0.0-beta.6版本移除了文件管理等功能，而生成的前端代码中有 import FileChoose from '@/components/FileChoose' 
<FileChoose ref="fileChoose" :dialog-form-visible="fileOpen" @confirm="getImgList" @close="fileClose" />
等代码，导致 npm run dev 报错，前端无法启动

**Comment by Cassuis** [comment]
问题1在dev分支已经修复了

**Comment by wenjianzhang** [comment]
go-admin 2.0.0-beta.7将修复这两个问题
