### ISSUE TITLE
## 启动时报错cache setup error, NOAUTH Authentication required

### ISSUE THREAD

**Issue by Yuji19** [go-admin-team/go-admin#463]
![图片](https://user-images.githubusercontent.com/38743137/123214103-64eb0080-d4f9-11eb-8d80-4f11da64fa99.png)
然后启动项目就报图中的错误，但是我本地连接的redis的密码是正确的，请问是配置文件哪里修改不对吗？
![图片](https://user-images.githubusercontent.com/38743137/123214283-98c62600-d4f9-11eb-91a4-948d8b60bd09.png)

**Comment by Cassuis** [comment]
这需要你去auth一下密码
redis-cli
auth 123456
config get requirepass
然后再去试试启动服务端

**Comment by holdonbaby** [comment]
我也同样情况报错了，lz解决了吗

**Comment by wenjianzhang** [comment]
新版本重新下载，不要cache使用memory即可

**Comment by honorjoey** [comment]
config.GetRedisClient()
确实是需要用到RedisClient的时候报这个错怎么办

**Comment by Cassuis** [comment]
> config.GetRedisClient() 确实是需要用到RedisClient的时候报这个错怎么办

如果有多数据源或者自己想自动以可以自己初始化redisclient用.

**Comment by honorjoey** [comment]
把github.com/go-redis/redis/v9降回v7解决了，好像是和redis 5.0.8的问题

**Comment by honorjoey** [comment]
> 

把github.com/go-redis/redis/v9降回v7解决了，好像是和redis 5.0.8的问题

**Comment by honorjoey** [comment]
> > config.GetRedisClient() 确实是需要用到RedisClient的时候报这个错怎么办
> 
> 如果有多数据源或者自己想强自定义以可以自己初始化redisclient用.

把github.com/go-redis/redis/v9降回v7解决了，好像是和redis 5.0.8的问题
