### ISSUE TITLE
关于封装Pagenation、response的serializer

### ISSUE THREAD

**Issue by hokaso** [go-admin-team/go-admin#466]
![](https://z3.ax1x.com/2021/06/28/RNRoaq.png)

目前go-admin的架构中，dto可以理解为图中的Request Model，Response Model似乎并没有定义，仅仅复用了DB Model，未来有计划补充这部分的限制嘛，比如某些接口不一定返回所有字段给用户，就需要这方面的限制（参考mybatis），由于dto已经定义了，所以感觉仅补充receive这方面的序列化方法会是个比较好的完善方案；以及分页感觉也可以再封装为一个专有的方法，这样能够减少很多重复的代码。

**Comment by wenjianzhang** [comment]
Response Model这块目前确实是复用DB Model，这块还在考虑，后续会使用resp的model来生成swagger doc 输出信息。。。

**Comment by hokaso** [comment]
厉害了 感谢回复 以及之前加了群可以通过下嘛 说不定以后也可以参与维护下你们的项目哈哈（分页那个我看错了 确实有封装

**Comment by wenjianzhang** [comment]
> 厉害了 感谢回复 以及之前加了群可以通过下嘛 说不定以后也可以参与维护下你们的项目哈哈（分页那个我看错了 确实有封装

qq群已经满了，你可以使用微信叫我，可以进入微信群

**Comment by hokaso** [comment]
微信：Hocassian_Stanley_He
