### ISSUE TITLE
macOS Big sur 11.0 go  build不起来。

### ISSUE THREAD

**Issue by wihaohao** [go-admin-team/go-admin#470]
使用旧go.mod，go build
Executable requires at least macOS 11.0, but is being run on macOS 10.16, and so is exiting.
重新创建go.mod  go get 
cannot find module providing package github.com/go-admin-team/go-admin-core/sdk/service

**Comment by wenjianzhang** [comment]
使用的go-admin是什么版本的

**Comment by wihaohao** [comment]
最新的master分支，刚又重新拉了一下，还是一样。
 # github.com/shirou/gopsutil/disk
Executable requires at least macOS 11.0, but is being run on macOS 10.16, and so is exiting.
# github.com/shirou/gopsutil/cpu
Executable requires at least macOS 11.0, but is being run on macOS 10.16, and so is exiting.
# github.com/shirou/gopsutil/mem
Executable requires at least macOS 11.0, but is being run on macOS 10.16, and so is exiting.
# github.com/mattn/go-sqlite3
Executable requires at least macOS 11.0, but is being run on macOS 10.16, and so is exiting.

从提示上看，应该依赖的go-sqlite3、gopsutil与mac os不兼容的问题

**Comment by wenjianzhang** [comment]
目前作者使用的是macos 11.4 ，也欢迎您对10.16版本做出单独的分支适配或者pr。
