### ISSUE TITLE
mac go build error

### ISSUE THREAD

**Issue by Binzaga** [go-admin-team/go-admin#476]
github.com/go-admin-team/go-admin-core/sdk/pkg: package provided by github.com/go-admin-team/go-admin-core at latest version v1.3.4 but not at required version v1.3.5-rc.6.0.20210701142131-afcbe40a6a3b

**Comment by wenjianzhang** [comment]
将github.com/go-admin-team/go-admin-core/sdk和github.com/go-admin-team/go-admin-core版本设置一致即可

**Comment by Binzaga** [comment]
是一致的
github.com/go-admin-team/go-admin-core v1.3.5-rc.6.0.20210701142131-afcbe40a6a3b
github.com/go-admin-team/go-admin-core/sdk v1.3.5-rc.6.0.20210701142131-afcbe40a6a3b

**Comment by Binzaga** [comment]
拉的go-admin master分支

**Comment by wenjianzhang** [comment]
可以改为 v1.3.6 版本号
