### ISSUE TITLE
windows无法go build

### ISSUE THREAD

**Issue by qixy13** [go-admin-team/go-admin#482]
**Describe the bug**
# github.com/mattn/go-sqlite3
cgo: exec gcc: exec: "gcc": executable file not found in %PATH%

**To Reproduce**
我按照教程下载了64位的mingw，也解压缩添加到环境变量里了，还是无法编译

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lukoozhao** [comment]
同样的问题

**Comment by lcsin** [comment]
+1

**Comment by lcsin** [comment]
可以试试下载mingw64位的第一个安装包
![image](https://user-images.githubusercontent.com/49903755/125724932-05c82bd7-0245-4d19-8be9-638fcbcb47cb.png)
