### ISSUE TITLE
[BUG] 修改用户其它信息导致密码被置空，数据权限

### ISSUE THREAD

**Issue by lx32056127** [go-admin-team/go-admin#484]
1.修改用户其它信息导致密码被置空

https://github.com/go-admin-team/go-admin/blob/90b17e995aa79d5ea120cbb514b6b5a6c03378b2/app/admin/service/dto/sys_user.go#L112-L114

判断内容不为空就可以了
```
	model.Username = s.Username
	if s.Password != "" {
		model.Password = s.Password
	}
	model.NickName = s.NickName
```

2.数据权限限定了本部门或者本人数据，实际上还是可以看到上级部门或下级部门的数据。
这个问题是我理解错了吗?

3.另外存在子角色新增用户的时候，可以选择顶级角色。。。
这里的角色不应该只能选择当前角色的子角色吗？同样的，部门跟岗位都有这个问题。

4.新增用户时没有将controlBy赋值给model，导致数据权限未能正常生效。

**Comment by Cassuis** [comment]
这样写会导致问题。因为db.save的时候有个PreHook。会让密码再次被加密。
