### ISSUE TITLE
为什么项目中sql文件中没有建表语句呢？

### ISSUE THREAD

**Issue by cz7154** [go-admin-team/go-admin#494]
全部都是INSERT INTO 语句···，难道表字段还要我们自己手动对照字段创建吗？

**Comment by Angry-Chick** [comment]
这个项目用的是 gorm 自动建表，在 cmd/migration，我记得文档里有个命令说了是创建表同时初始化数据

**Comment by wenjianzhang** [comment]
https://doc.go-admin.dev/guide/ksks.html#%E5%88%9D%E5%A7%8B%E5%8C%96
