### ISSUE TITLE
部门管理中，出现 leader不能为空

### ISSUE THREAD

**Issue by lyplay2** [go-admin-team/go-admin#496]
删除所有部门后，新建部门，点保存时 报错 “leader不能为空”

**Comment by Angry-Chick** [comment]
![image](https://user-images.githubusercontent.com/26614913/126096533-aa5d6868-de58-41ce-a399-bf36a1b2d561.png)
那是因为后端对 leader 做了检查，实际上应该是前端忘了把负责人字段标记为必填，你填个负责人就好了

**Comment by wenjianzhang** [comment]
https://github.com/go-admin-team/go-admin-ui/commit/cf820eb9aa061e57a7e221db170bf614112fc963
