### ISSUE TITLE
请作者简要介绍一下 自定义API 的步骤

### ISSUE THREAD

**Issue by lyplay2** [go-admin-team/go-admin#497]
我想 写一些 自己的API 供 小程序使用。请问该如何做？谢谢

**Comment by Angry-Chick** [comment]
我觉得吧，你先把 api 导入进去，创建对应的菜单关联，然后创建角色关联菜单，最后将用户关联角色。有些缺失的接口自己实现以下

**Comment by wenjianzhang** [comment]
https://doc.go-admin.dev/guide/intro/tutorial01.html#%E7%BC%96%E5%86%99%E7%AC%AC%E4%B8%80%E4%B8%AA%E6%8E%A5%E5%8F%A3
