### ISSUE TITLE
 go-admin 2.0.0版本的行政区管理、文件管理、内容管理无法打开

### ISSUE THREAD

**Issue by qinglingzhiqing** [go-admin-team/go-admin#498]
问题如题，我checkout了v2.0.0版本，当然其他版本也试了，发现无法打开行政区管理、文件管理、内容管理；
但是我看线上的Demo是有这几个功能的。
请问是有什么额外的设置吗？

**Comment by Angry-Chick** [comment]
怎么说呢，我拉的是 master 代码，也是打不开你说的这几个页面，看 network 实际上没有往后端发请求，而且后端我看了没有这几个接口了，应该是这几个功能阉割了

**Comment by wenjianzhang** [comment]
> 问题如题，我checkout了v2.0.0版本，当然其他版本也试了，发现打不开行政区管理、文件管理、内容管理；
> 但是我看网上的Demo是有这几个功能的。
> 请问是有什么额外的的设置吗？

2.0.0 版本将行政区管理、文件管理、内容管理等功能移除，考虑到这些功能更偏向业务，在新功能中不在考虑，如果需要可以参考2.0.0升级的调整将之前版本中的内容升级即可；
