### ISSUE TITLE
sys_menu_api_rule中的数据生成的错误

### ISSUE THREAD

**Issue by jason7758** [go-admin-team/go-admin#499]
今天查用户为什么授权后，依然没有权限访问，发现是sys_menu_api_rule表中的api与menu表的数据对应不上，请问这个数据表中的数据也是启动时生成的吗。

![image](https://user-images.githubusercontent.com/382997/126260932-eedb12a3-f0c5-4dfa-8dae-03e5d36859d7.png)

![image](https://user-images.githubusercontent.com/382997/126260965-2f094a03-36ae-4978-9e8c-4397ba6af8d1.png)

**Comment by Angry-Chick** [comment]
sys_menu_api_rule 是一个多对多的连接表，表和数据是初始化的时候生成的，当你创建一个菜单并设置了对应的 api，就会自动在该连接表中创建记录
![image](https://user-images.githubusercontent.com/26614913/126288269-e5f008a8-d722-4314-97a0-5b6b89268302.png)

**Comment by jason7758** [comment]
> sys_menu_api_rule 是一个多对多的连接表，表和数据是初始化的时候生成的，当你创建一个菜单并设置了对应的 api，就会自动在该连接表中创建记录
> ![image](https://user-images.githubusercontent.com/26614913/126288269-e5f008a8-d722-4314-97a0-5b6b89268302.png)

把流程梳理了一下，已经搞明白了，
一、 权限问题

1、 权限是通过查询sys_casbin_rule表，来实现的如：
```
SELECT * FROM sys_casbin_rule where v0 = "Test" AND v1 ="/api/v1/whisper" AND v2 = "GET"
```
手动写入数据需要重新项目才能生效

2、 系统更新权限流程：
2.1、 api初如化

系统初始化-> 
```
go-admin server -c=config/settings.dev.yml -a=true
```
默认情况下为false,当设置为true时，就会对当前程序所有的 api 进行检查并创建生成api信息，写入sys-api表
在apis/上function 中，编写swagger 注释，刚会成生api对就在的title
api可以在系统的【系统管理】-> 【接口管理】中看到

2.2 、 创建菜单:
创建菜单- api权限中选择对应的api 并授权，这样授权了，这个菜单权限的角色，将可以访问对应api
对应的记录保存在sys_menu_api_rule表。 

2.3、 给用户授权
编辑用户，选择对应权限则用户就会继承自用户所属角色的权限

2.4、 界面所显示按钮权限控制
是通过菜单上配置的『权限标识』用户授权此菜单后，在前端的ui按钮上代码上对应写上
v-permisaction="['admin:whisper:audit']" 来实现的。

2.5、重新配置菜单与api授权
如果出现菜单有权限，但访问请求提示没有权限 ，请菜单上的授权的api是不是正确，确实api的path正确，然后菜单上重新授权 api，
然后还需要在角色管理中重新给这个角色授权菜单权限。
