### ISSUE TITLE
菜单的目录显示不正确

### ISSUE THREAD

**Issue by jason7758** [go-admin-team/go-admin#500]
给角色分配的不是这个目录的所有菜单，那么登录后目录就没有正常显示出来，也就看不到别的菜单。
![image](https://user-images.githubusercontent.com/382997/126463688-580cbdee-9603-4e7e-add7-17e4b1cd26f9.png)

![image](https://user-images.githubusercontent.com/382997/126463727-8e2c6854-79f8-45c2-8cc8-36ea5a264996.png)

如果把目标下的所有菜单都授权后，刚会正常显示
![image](https://user-images.githubusercontent.com/382997/126463951-f30c6b2f-3817-4418-acbf-a16c09a5bdb9.png)

![image](https://user-images.githubusercontent.com/382997/126464050-91023202-a335-459c-965a-f0d61f14fe80.png)

**Comment by wenjianzhang** [comment]
是哪个版本？
