### ISSUE TITLE
CasbinRule需要手工修改数据库么

### ISSUE THREAD

**Issue by safejob** [go-admin-team/go-admin#502]
model里面有CasbinRule 数据库里也有相对应的表  但是在前端并没有配置的地方
要对接口设置角色权限 需要手动修改数据库么

**Comment by safejob** [comment]
现在新创建的角色 授权访问某个页面时，会提示没有接口权限  但没有授予接口权限的地方呢  帮看看  是我操作不对么

**Comment by lain1936** [comment]
可以在菜单管理里添加角色的接口权限

**Comment by safejob** [comment]
菜单管理里的授权是什么意思，是前端代码里用的权限么？ 菜单管理里的权限授权是怎么用的呢，也没有显示是授权到某个角色呀

**Comment by lain1936** [comment]
流程上应该是这样

先菜单管理
可以参考现有的用户，岗位的接口权限的结构，手动添加  （有些字段我也不清楚，按钮菜单是隐藏的）
或者导入表结构，使用代码生成时候会生成对应的导航菜单以及按钮菜单权限

然后角色管理
角色的菜单权限，勾选对应的菜单（这里会插入CasbinRule）

然后路由有用到AuthCheckRole中间件就会使用到权限检查

**Comment by safejob** [comment]
版本 2.0.0
代码中没有找到有向casbin数据库表插入数据的代码 手动插入能解决问题

**Comment by safejob** [comment]
解决了  确实需要按你上面说的流程
菜单管理里面可以为菜单项目关连对应的api
然后在角色管理的时候 选择相应的菜单权限，实际上也顺带把对应的api权限写到casbin了
