### ISSUE TITLE
问题：怎么解决在使用go-admin时添加用户失败，并弹出invalid parameter: DeptId的错误提示。

### ISSUE THREAD

**Issue by liuliuxy** [go-admin-team/go-admin#506]
问题：怎么解决在使用go-admin时添加用户失败，并弹出invalid parameter: DeptId的错误提示。
![image](https://user-images.githubusercontent.com/42893359/126773038-16c3d41a-a5eb-49ca-aca5-7eb27eb6299c.png)
系统：windows10
数据库：MySql8.0
go v1.15.6 windows/amd64
nodejs v14.15.0.

**Comment by safejob** [comment]
我也遇到了  退回 v2.0.0 正常

**Comment by ShakaGuo** [comment]
移除 对应 modle中的 VD验证部分既可。
