### ISSUE TITLE
顶部TopNav菜单挪到其他菜单下无效

### ISSUE THREAD

**Issue by songning4** [go-admin-team/go-admin#508]
想把顶部菜单中有关系统自带的功能挪到“系统管理”里面，怎么配置都出错，求告知，参照日志目录填写一样无效

**Comment by wenjianzhang** [comment]
已经菜单转移到二级目录下需要注意`组件路径`的配置，具体配置可以参考 https://panjiachen.gitee.io/vue-element-admin-site/zh/guide/essentials/router-and-nav.html#%E5%A4%9A%E7%BA%A7%E7%9B%AE%E5%BD%95-%E5%B5%8C%E5%A5%97%E8%B7%AF%E7%94%B1
