### ISSUE TITLE
问题：如何触发sys_api表添加新接口apis

### ISSUE THREAD

**Issue by safejob** [go-admin-team/go-admin#509]
![图片](https://user-images.githubusercontent.com/62788572/127088926-4fd66bbb-269c-421b-8fdd-ce705be62625.png)
使用 开发工具>代码生成 创建的内容，在使用配置迁移脚本和配置生成的方式 均没有将接口存到 sys_api 表, 导致无法对接口进行权限管理。 请问  怎样才会触发该表更新呢

**Comment by wenjianzhang** [comment]
server命令调整，新增-a参数，默认为false，新增接口后可以设置为true状态，系统会自动添加接口数据
