### ISSUE TITLE
最新版master版本删除部门bug

### ISSUE THREAD

**Issue by songning4** [go-admin-team/go-admin#510]
![D58AD3C1F97B04D4589B005CA89DEA7E](https://user-images.githubusercontent.com/65797035/127089397-8d95cf47-44fc-406d-974e-8c16f23fb16b.jpg)

![2B2725DF28A995EB890ED4DD2BEC327E](https://user-images.githubusercontent.com/65797035/127089416-95361f00-5c1b-434f-aac6-4ac4ebb01fcb.jpg)

![7335E8D43B0DD6BCD915895CB2B9C86D](https://user-images.githubusercontent.com/65797035/127089443-e49937a3-3571-4500-977c-a16871928163.jpg)

![17C9CBD3D861DDAD6E66642E60ED3F62](https://user-images.githubusercontent.com/65797035/127089453-d55f549f-acc8-4b47-87d9-02b9a0d46b0e.jpg)

最新版master版本部署好后删除部门提示删除失败，调试发现获取数据为空，修改了结构体的定义后正常，希望管理员能更新下master版本，谢谢

**Comment by wenjianzhang** [comment]
前端传参问题，以调整
