### ISSUE TITLE
用户修改menu授权，角色权限不会自动更新

### ISSUE THREAD

**Issue by majintao** [go-admin-team/go-admin#512]
用户修改菜单menu授权的权限，相关的角色在casbin表 不会更新新的权限绑定角色；需要 在角色管理重新update一下数据，触发新数据casbin的生成  （bug）

**Comment by wenjianzhang** [comment]
目前需要执行完后，手动触发角色更新；
后续会优化改进

**Comment by majintao** [comment]
好久了，目测还没优化..

**Comment by majintao** [comment]
@wenjianzhang

**Comment by wenjianzhang** [comment]
这个我们经过考虑暂缓了优化；
因为在给菜单变更权限的同时并不确定影响到了多少个角色；或者有哪些角色实际上是不需要这个权限的，所以不能联动变更角色的权限。

**Comment by dangweiwu** [comment]
这个问题可以优化的，遍历就可以了，角色中都带着菜单id呢，把所有角色包含的菜单ID遍历一遍就知道哪些角色应该更新，这也是可以实现的，因为现实中角色不可能有很多，遍历一遍很快的，机器去做，总比手动去做要好的多。
