### ISSUE TITLE
代码生成器，生成下拉出错，显示

### ISSUE THREAD

**Issue by dingke198** [go-admin-team/go-admin#517]
![image](https://user-images.githubusercontent.com/20252870/127734483-bc283f73-3242-4652-ade2-b53d4c392a7c.png)
![image](https://user-images.githubusercontent.com/20252870/127734503-a285f5f2-939f-4881-a51a-5108073cd8fd.png)
要手动改这两地方才能显示出来

**Comment by songning4** [comment]
@dingke198 非常感谢，我刚生成代码也是遇到这个问题，用上面的方法可行
