### ISSUE TITLE
请教菜单关联问题

### ISSUE THREAD

**Issue by songning4** [go-admin-team/go-admin#518]
在研究代码时遇到问题：
sys_menu_api_rule和sys_menu在go里面哪里做关联的，研究代码一直没搞懂这块，麻烦告知一下，谢谢

**Comment by wenjianzhang** [comment]
看sys_menu相关代码

**Comment by songning4** [comment]
就是因为看了没有看到任何关联信息才来这里请教的，麻烦告知一下，谢谢
