### ISSUE TITLE
最新版版本，新建菜单接口，接口实现逻辑没有关联到api授权相关数据，只是对sys_menu表插入了一条数据

### ISSUE THREAD

**Issue by Qiufcong** [go-admin-team/go-admin#520]
**Describe the bug**
最新版版本，新建菜单接口，接口实现逻辑没有关联到api授权相关数据，只是对sys_menu表插入了一条

**Comment by wenjianzhang** [comment]
这个需要在menu相关配置中配置对应的api，菜单和按钮是可以配置api的
