### ISSUE TITLE
2.0.2版本抽屉右上角关闭按钮无效

### ISSUE THREAD

**Issue by songning4** [go-admin-team/go-admin#522]
<img width="911" alt="1" src="https://user-images.githubusercontent.com/65797035/127995175-02d47375-a5fe-47ee-a811-30c707317d69.png">

点开抽屉后点击关闭按钮无效

**Comment by songning4** [comment]
![image](https://user-images.githubusercontent.com/65797035/127998228-c97a1c22-bdda-4f29-8f3f-948cc3edc080.png)
演示站的也不能关闭

**Comment by wenjianzhang** [comment]
https://github.com/go-admin-team/go-admin-ui/commit/243b73c965d404fc943534f4b8495c7eb55ee356
