### ISSUE TITLE
sqlite 数据库初始化失败

### ISSUE THREAD

**Issue by JieGe00** [go-admin-team/go-admin#536]
./go-admin.exe migrate -c=config/settings.sqlite.yml
start init
2021/08/16 16:21:52 CreateFile temp/logs: The system cannot find the path specified.
2021-08-16 16:21:52.980+0800 file:database/initialize.go:31 level:info * => sqlite3.db
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xed05e9]

goroutine 1 [running]:
github.com/go-admin-team/go-admin-core/tools/database.(*DBConfig).Init(0xc0003bd950, 0xc00034c000, 0x0, 0x7, 0x3175300, 0x3)
        D:/script/Go/pkg/mod/github.com/go-admin-team/go-admin-core@v1.3.7/tools/database/config.go:39 +0x49
go-admin/common/database.setupSimpleDatabase(0x2929396, 0x1, 0xc00009b800)
        D:/script/Go/src/goadmin/go-admin/common/database/initialize.go:41 +0x687
go-admin/common/database.Setup()
        D:/script/Go/src/goadmin/go-admin/common/database/initialize.go:23 +0xd9
go-admin/cmd/migrate.initDB()
        D:/script/Go/src/goadmin/go-admin/cmd/migrate/server.go:80 +0x2d
github.com/go-admin-team/go-admin-core/sdk/config.(*Settings).runCallback(0xc00067d680)
        D:/script/Go/pkg/mod/github.com/go-admin-team/go-admin-core/sdk@v1.3.7/config/config.go:24 +0x44
github.com/go-admin-team/go-admin-core/sdk/config.(*Settings).init(0xc00067d680)
        D:/script/Go/pkg/mod/github.com/go-admin-team/go-admin-core/sdk@v1.3.7/config/config.go:41 +0xa6
github.com/go-admin-team/go-admin-core/sdk/config.(*Settings).Init(0xc00067d680)
        D:/script/Go/pkg/mod/github.com/go-admin-team/go-admin-core/sdk@v1.3.7/config/config.go:34 +0x32
github.com/go-admin-team/go-admin-core/sdk/config.Setup(0x2967738, 0xc0003a9320, 0xc000510220, 0x1, 0x1)
        D:/script/Go/pkg/mod/github.com/go-admin-team/go-admin-core/sdk@v1.3.7/config/config.go:96 +0x24b
go-admin/cmd/migrate.run()
        D:/script/Go/src/goadmin/go-admin/cmd/migrate/server.go:51 +0x1a5
go-admin/cmd/migrate.glob..func1(0x23c0e60, 0xc0000a8da0, 0x0, 0x1)
        D:/script/Go/src/goadmin/go-admin/cmd/migrate/server.go:33 +0x27
github.com/spf13/cobra.(*Command).execute(0x23c0e60, 0xc0000a8d90, 0x1, 0x1, 0x23c0e60, 0xc0000a8d90)
        D:/script/Go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x23c03e0, 0xf93ed0, 0x0, 0x1)
        D:/script/Go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        D:/script/Go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
go-admin/cmd.Execute()
        D:/script/Go/src/goadmin/go-admin/cmd/cobra.go:54 +0x34
main.main()
        D:/script/Go/src/goadmin/go-admin/main.go:20 +0x27

**Comment by wenjianzhang** [comment]
目前不支持sqlite初始化

**Comment by joyhope** [comment]
sqlite3 编译要增加tag, go build -tags sqlite3 (我看代码是这样的）

但是 最终执行还是遇到了错误

go-admin/app/admin/service/sys_config.go:176 no such column: sys_config.is_frontend [0.231ms] [rows:0] SELECT * FROM `sys_config` WHERE `sys_config`.`is_frontend` = 1 AND `sys_config`.`deleted_at` IS NULL

是否默认的sqlite3.db 比较老，没有同步到最新的代码。
