### ISSUE TITLE
编辑put提交json数据，数据验证问题

### ISSUE THREAD

**Issue by bjhxcx** [go-admin-team/go-admin#537]
Request URL: http://127.0.0.1:8000/api/v1/report-tpl/4
Request Method: PUT
Status Code: 200 OK
提交数据如下:{"id":4,"name":"测试","tplUniqueCode":"20b49bdbea6d4b2f87b70ca2ae165275","remark":"","queryParams":"","settings":null,"createdAt":"2021-08-16T22:19:18.579+08:00","updatedAt":"2021-08-16T22:42:56.581+08:00","createBy":0,"updateBy":0}
dto中的接收数据的结构体:
type ReportTplUpdateReq struct {
	Id          int    `uri:"id" comment:""` //
	Name        string `json:"name" comment:"报表名称22" binding:"required"`
	Remark      string `json:"remark" comment:"备注"`
	QueryParams string `json:"queryParams" comment:"查询参数"`
	common.ControlBy
}
编辑提交数据时有时可以成功,有时提示 "报表名称22为必填字段"
我使用了gin的bindJson 可以正常验证数据

**Comment by wenjianzhang** [comment]
项目目前使用的是https://github.com/bytedance/go-tagexpr 第三方验证组件，请正确使用即可，
 Leader   string `json:"leader" comment:"负责人" vd:"@:len($)>0; msg:'leader不能为空'"` //负责人
