### ISSUE TITLE
bug：修改头像并提交后，密码也会被改了

### ISSUE THREAD

**Issue by jason-wj** [go-admin-team/go-admin#538]
RT

**Comment by wenjianzhang** [comment]
体完整的描述您的问题！

**Comment by jason-wj** [comment]
> 请完整的描述您的问题！

后台账户登录后，修改账户资料那里，剪裁变更头像并提交后，当前账户的密码也被改了。
调试跟踪后发现，应该是更新头像时，调用的save保存的SysUser，密码又被二次加密了。

**Comment by wenjianzhang** [comment]
最新版本吗？

**Comment by zhr930219** [comment]
我也发现这问题了，更新头像后，就无法登陆了

**Comment by chen-shiwei** [comment]
> > 请完整的描述您的问题！
> 
> 后台账户登录后，修改账户资料那里，剪裁变更头像并提交后，当前账户的密码也被改了。 调试跟踪后发现，应该是更新头像时，调用的save保存的SysUser，密码又被二次加密了。

我也遇到了，是gorm 更新结构体的所有字段覆盖了

**Comment by brucewangzhihua** [comment]
//密码长度小于60是没有加密过的密码，更新前需要加密
func (e *SysUser) BeforeUpdate(_ *gorm.DB) error {
	var err error
	if len(e.Password) < 60 {
		err = e.Encrypt()
	}
	return err
}

**Comment by brucewangzhihua** [comment]
导致这个问题的原因是更新用户任何信息都是全量更新，而更新前埋了一个钩子对密码进行了一次加密。这样就造成了二次加密
