### ISSUE TITLE
修改用户角色权限时. 提交后, sys_casbin_rule 表被全部更新. 只有 common_user的信息

### ISSUE THREAD

**Issue by allenLew1991** [go-admin-team/go-admin#539]
![image](https://user-images.githubusercontent.com/3362015/129709538-291ed238-30e7-4906-8ef5-8c0ec54f00ec.png)

**Comment by wenjianzhang** [comment]
请详细描述您的问题！

**Comment by Air-Smile** [comment]
@wenjianzhang 这问题确实存在，如果我添加新的模块的接口（动作），那么想设置权限的时候，我发现sys_casbin_rule 表里第一次有 添加的模块权限。当我再去修改后，sys_casbin_rule 表的数据会被清除，然后再次添加进来，但却没新模块的接口权限

**Comment by wenjianzhang** [comment]
> @wenjianzhang 这问题确实存在，如果我添加新的模块的接口（动作），那么想设置权限的时候，我发现sys_casbin_rule 表里第一次有 添加的模块权限。当我再去修改后，sys_casbin_rule 表的数据会被清除，然后再次添加进来，但却没新模块的接口权限

需要将API绑定对应的按钮，然后赋权即可。

**Comment by zhouxixi-dev** [comment]
@wenjianzhang 不管是
// Update 修改SysRole对象
func (e *SysRole) Update(c *dto.SysRoleUpdateReq, cb *casbin.SyncedEnforcer) error {
       // ....
	_ = cb.SavePolicy()
	return nil
}

**Comment by zhouxixi-dev** [comment]
@wenjianzhang 不管是 Insert SysRole，还是 Update SysRole，里面都有一行`cb.SavePolicy()`的代码，这行代码会调用[https://github.com/go-admin-team/gorm-adapter/blob/master/adapter.go](https://github.com/go-admin-team/gorm-adapter/blob/master/adapter.go)中的`SavePolicy`方法，该方法会先 dropTable，然后再 createTable，如下图所示：
![image](https://user-images.githubusercontent.com/100399679/172778460-be7e19c3-c2a0-4f51-bc77-0e839070a676.png)

```
// Insert 创建SysRole对象
func (e *SysRole) Insert(c *dto.SysRoleInsertReq, cb *casbin.SyncedEnforcer) error {
       // .....
	_ = cb.SavePolicy()
	return nil
}

// Update 修改SysRole对象
func (e *SysRole) Update(c *dto.SysRoleUpdateReq, cb *casbin.SyncedEnforcer) error {
    // ....
    _ = cb.SavePolicy()
    return nil
}
```

**Comment by goople8** [comment]
我5月也是遇到这个问题，用户反馈权限怎么忽然就没有了，后来我发现，管理员更改角色菜单授权是，点保存，会把sys_casbin_rule 表里对应角色的数据清空，然后再重新insert，可问题就是居然插入的数据有时一条都没有插进去，有时有缺少一些数据，时多时少，反正不稳定。这个地方一定要改进才行

**Comment by tlyyxjz** [comment]
这个「改角色授权时 sys_casbin_rule 被清空再重新插入、偶尔还丢数据」的问题，本质上是 go-admin 在 SavePolicy 时的时序/事务问题，好几位都踩过。

我想补充一个排查角度：以后遇到「权限忽然没了/不全」，可以用我做的开源工具 casbin-config-doctor（Go 版 authztest）在出事前后的 policy 快照上做 near-miss 比对，快速看出是哪些规则没写进去、是不是重复键冲突。

开源在 github.com/tlyyxjz/casbin-config-doctor。有谁后来彻底解决过这个丢权限的问题吗？想确认下最终根因，也欢迎试用我的工具看能不能帮上忙。
