### ISSUE TITLE
当前request无权限，请管理员确认！

### ISSUE THREAD

**Issue by Roger-G** [go-admin-team/go-admin#548]
接口权限 和菜单权限分开了，建议教程出下这个版本的使用方式，无数次错误 bug

**Comment by wenjianzhang** [comment]
可以进群了解

**Comment by Air-Smile** [comment]
@wenjianzhang 没人加，加了很多次

**Comment by goople8** [comment]
@wenjianzhang  同样的，从去年加到今年，硬是没人放行

**Comment by wenjianzhang** [comment]
进群问题回答了吗？

**Comment by Air-Smile** [comment]
没人加

**Comment by wenjianzhang** [comment]
应该是没看到，你加一下我的微信，文档中有

**Comment by wenjianzhang** [comment]
> 没人加
进群了吗？

**Comment by wenjianzhang** [comment]
> @wenjianzhang 同样的，从去年加到今年，硬是没人放行

进群了吗？

**Comment by goople8** [comment]
神了，未必你不是群主？看不到别人的加群信息？ 或者说QQ屏蔽了你的群加群信息？我还还没进群呢，加群信息石沉大海！！！

**Comment by crystalww** [comment]
这个问题有解决方案嘛

**Comment by shanezhiu** [comment]
为什么一个在issue提出的问题，却要到QQ群里才能回答？
