### ISSUE TITLE
希望早日支持postgresql数据库。

### ISSUE THREAD

**Issue by hametan** [go-admin-team/go-admin#554]
希望早日支持postgresql数据库。

**Comment by hametan** [comment]
目前自己想办法把数据库迁到pgsql了，但是发现受go-admin-core影响，还是有问题，主要体现在 ` 操作符上。

**Comment by infnan** [comment]
以下是workaround，供其他搜索到此条issue的人参考：

1. 自己fork一份 go-admin-core，把 tools/search/query.go 中的单撇号删掉，然后修改go.mod，加入
```
replace github.com/go-admin-team/go-admin-core v1.3.8 => github.com/你fork的地方/go-admin-core 改完的commit版本
replace github.com/go-admin-team/go-admin-core/sdk v1.3.9 => github.com/你fork的地方/go-admin-core/sdk 改完的commit版本
```
2. 按 #187 改 config/db.sql。具体改法是把前两行语句和最后一行语句删掉，然后把单撇号删掉。
3. 修改go-admin的以下文件，把部分写成int的都改成string：
    * app/admin/apis/sys_config.go:201：加引号，改成`req.IsFrontend = "1"`
    * app/admin/models/sys_config.go：13行的IsFrontend类型改成string
    * app/admin/service/dto/sys_config.go：15行、32行、46行的int改成string
    * cmd/migrate/migration/init.go：49行的`"version = ?", v`的v转成字符串`strconv.Itoa(v)`
    * common/middleware/handler/login.go：17行的`status = 2`加引号`status = '2'`

**Comment by 107295472** [comment]
希望加入dapr微服务的支持

**Comment by wenjianzhang** [comment]
已经支持pgsql

**Comment by lchjczw** [comment]
改完了，才发现这里有同行已经改过了，不过现在的版本在苹果新的m1上还有问题：
`github.com/shirou/gopsutil`这个包需要更新到`github.com/shirou/gopsutil/v3`，并且
```
	github.com/alibaba/sentinel-golang v1.0.5-0.20220111070554-683c229b23a9
	github.com/alibaba/sentinel-golang/pkg/adapters/gin v0.0.0-20220111070554-683c229b23a9

```
这两个包也要更新到最新的，这样在m1上就没发现问题了

另外就是布尔值，究竟直接存字符串1，还是直接存储布尔值，另外里面的状态值，存储字符串的数字，感觉不好，我们之前的系统也是这样，现在改成存储有意义的字符串，比如："disable","enable"等字符串，用来更明确的表达状态
