### ISSUE TITLE
升级到2.0 单独写了一个加了应用模块，接口报404

### ISSUE THREAD

**Issue by jackluo2012** [go-admin-team/go-admin#559]
![image](https://user-images.githubusercontent.com/2638586/137285671-4ec3a586-d981-4a99-81f0-56ca17935279.png)
![image](https://user-images.githubusercontent.com/2638586/137286213-48550a05-2038-4e6d-8d81-1f322b79a912.png)

生成的api 报404

**Comment by wenjianzhang** [comment]
首先要使用cmd创建应用，然后再生成
