### ISSUE TITLE
redis的使用案例，能不能给个redis案例

### ISSUE THREAD

**Issue by dingke198** [go-admin-team/go-admin#567]
这里面没有看到redis的使用案例，能不能给个redis案例

**Comment by nottellyou** [comment]
我也想知道

**Comment by nottellyou** [comment]
import (
	"github.com/go-admin-team/go-admin-core/sdk/config"
	runtimex "github.com/go-admin-team/go-admin-core/sdk/runtime"
	"github.com/go-admin-team/go-admin-core/storage"
)
	cacheAdapter, _ := config.CacheConfig.Setup()
	redisX := runtimex.NewCache("xxx", cacheAdapter, "")
然后就可以正常使用了。目前在service目录里的文件可以正常使用。

花了我几个小时找到了。前提条件：在配置文件里配置redis相关参数。

**Comment by zengchengjie** [comment]
为什么我存储进去的redis数据，都带一个斜杠   / ？
![Uploading image.png…]()
