### ISSUE TITLE
生成代码的内容有问题

### ISSUE THREAD

**Issue by maliyan** [go-admin-team/go-admin#569]
按照[这个示例](https://doc.go-admin.dev/guide/intro/tutorial02.html#%E8%A1%A8%E7%BB%93%E6%9E%84%E5%AF%BC%E5%85%A5)生成代码之后，发现 `app/admin/service/dto/article.go`内容生成的有问题，会导致请求这个示例路径404：`http://127.0.0.1:8000/api/v1/article?pageIndex=1&pageSize=10&beginTime=&endTime=`

如下图：

![image](https://user-images.githubusercontent.com/5624855/140469049-aad5ecf0-5a4d-41a2-9972-3c34a8a5c07f.png)

__解决方案：__ 修改`template/v4/dto.go.template:18`文件，将最后的一个`-`去掉，保证了time包会"追加"到上一个包的后面。
![image](https://user-images.githubusercontent.com/5624855/140695950-25927d13-740f-41c1-91f1-c77434701e38.png)

---------------------------------

这个文件也缺少import time包：`app/admin/service/article.go`

![image](https://user-images.githubusercontent.com/5624855/140471015-4e9358a8-b312-49ab-8310-2c2dbafd11c6.png)

**Comment by wenjianzhang** [comment]
done
