### ISSUE TITLE
后台刷新出现404

### ISSUE THREAD

**Issue by songning4** [go-admin-team/go-admin#571]
正常登陆后台，所有功能都可以使用，但是一旦刷新网页就会出现404，必须重新输入http://domain/才能再次访问后台

**Comment by wenjianzhang** [comment]
系统默认功能吗？

**Comment by songning4** [comment]
> 系统默认功能吗？

是的，不过现在已经解决了，之前是用的官方文档Nginx配置
https://doc.go-admin.dev/guide/hjbs.html#nginx-%E9%85%8D%E7%BD%AE
后来改了一下Nginx配置，加了一句：
try_files $uri $uri/ /index.html
