### ISSUE TITLE
多库数据如何配置？

### ISSUE THREAD

**Issue by blue7wings** [go-admin-team/go-admin#574]
我go-admin的数据表全部在go-admin数据库中，而需要使用的数据表全部在main库中，这种如何写配置文件呢？

**Comment by ebedevelopment** [comment]
+1

**Comment by wenjianzhang** [comment]
https://gorm.io/zh_CN/docs/dbresolver.html

**Comment by wenjianzhang** [comment]
[多库数据配置](https://doc.go-admin.dev/configure#%E4%B8%9A%E5%8A%A1%E5%88%86%E5%BA%93)

**Comment by knight0zh** [comment]
> 我go-admin的数据表全部在go-admin数据库是mysql，业务数据在另一个pgsql库里，应该如何设置，是否支持？
