### ISSUE TITLE
对不起，您没有该接口访问权限，请联系管理员

### ISSUE THREAD

**Issue by isonz** [go-admin-team/go-admin#577]
最新版的 v2.0.7
我按照文档，新建了一个 article 表并按步骤执行，一切都正常。
也运行了：
go-admin server -c=config/settings.dev.yml -a=true
接口管理有数据。

但是角色管理里面的菜单权限，只有：

系统管理
开发工具
定时任务
系统工具
文章管理

这5个选项和字选项，没有视频教程里面的 “接口权限” 选项和子选项。

结果导致新角色对应的用户访问时就出现了：
code: 403
msg: "对不起，您没有该接口访问权限，请联系管理员"

请问怎么解，谢谢。
![WX20211130-230456](https://user-images.githubusercontent.com/117757/144073925-56b82efa-5488-48ed-b748-d7e65ca12e89.png)
![2](https://user-images.githubusercontent.com/117757/144073963-b81e03f2-5161-4cfe-8f6e-b5f7b8390e05.png)

**Comment by cjy135070** [comment]
> 最新版的 v2.0.7 我按照文档，新建了一个 article 表并按步骤执行，一切都正常。 也运行了： go-admin server -c=config/settings.dev.yml -a=true 接口管理有数据。
> 
> 但是角色管理里面的菜单权限，只有：
> 
> 系统管理 开发工具 定时任务 系统工具 文章管理
> 
> 这5个选项和字选项，没有视频教程里面的 “接口权限” 选项和子选项。
> 
> 结果导致新角色对应的用户访问时就出现了： code: 403 msg: "对不起，您没有该接口访问权限，请联系管理员"
> 
> 请问怎么解，谢谢。 ![WX20211130-230456](https://user-images.githubusercontent.com/117757/144073925-56b82efa-5488-48ed-b748-d7e65ca12e89.png) ![2](https://user-images.githubusercontent.com/117757/144073963-b81e03f2-5161-4cfe-8f6e-b5f7b8390e05.png)

接口的权限管理功能应该是修改了，不再像文档和视频里说明的那样了
1. 在sys_api表中手动插入所需的接口信息
2. 进入菜单管理，选中所需菜单或功能(分页获取、创建、修改这些) 点击操作栏的修改，在最下方的api权限中，将对应的接口授权到菜单或功能上
3. 进入角色管理界面，修改角色的菜单权限，选中提交后重新登录就可以使用了

意思是将接口的权限放在菜单上进行处理，但数据库中还是绑定在角色上的
会导致一个问题，如果修改了一个菜单包含的接口权限，但是没有修改角色的菜单权限，角色所拥有的应该还是之前的权限，有待设计

**Comment by isonz** [comment]
Good to know.
非常感谢您的帮助。按照您的方法，在sys_api表中手动插入所需的接口信息，我的程序成功运行了。
但是还有一个小问题。
<img width="728" alt="1" src="https://user-images.githubusercontent.com/117757/144705202-8c4b176b-6666-4fe5-b094-1e6b9cc4474c.png">

当字段是日期型的时候，input 的类型没有变成 date 类型，填写日期的时候就要用键盘打进去。
另外就是，当信息保存后再修改时，日期型会自动变成 T00:00:00+08:00 格式，这样的话点保存数据库是会报错，保存不了数据的。必须把这段去掉才行。

<img width="126" alt="2" src="https://user-images.githubusercontent.com/117757/144705275-424f5234-f612-4df3-8137-ed47144e8950.png">

希望您能在下一个版本修复一下，非常感谢您的付出。

**Comment by Xihuyouyu** [comment]
> 

初始化数据库的时候，菜单所需要的接口授权不完整导致的，其实你自己补上也是可以的。

**Comment by isonz** [comment]
我觉得你们这样把权限集成到菜单是比较好的设计，比起隔壁的go-vue-admin要好，更改权限时不需要到菜单和角色里修改2个地方，在菜单里一次搞定。

**Comment by Stonelalala** [comment]
1：./go-admin server -c=config/settings.dev.yml -a=true 重新跑一下创建接口
2：菜单里面重新勾选 
这样就不会提示没有权限了

**Comment by SomnusBin** [comment]
> 视频
在最下方的api权限中，将对应的接口授权到菜单或功能上
这个api权限在哪里呢

**Comment by SomnusBin** [comment]
> > 最新版的 v2.0.7 我按照文档，新建了一个 article 表并按步骤执行，一切都正常。 也运行了： go-admin server -c=config/settings.dev.yml -a=true 接口管理有数据。
> > 但是角色管理里面的菜单权限，只有：
> > 系统管理 开发工具 定时任务 系统工具 文章管理
> > 这5个选项和字选项，没有视频教程里面的 “接口权限” 选项和子选项。
> > 结果导致新角色对应的用户访问时就出现了： code: 403 msg: "对不起，您没有该接口访问权限，请联系管理员"
> > 请问怎么解，谢谢。 ![WX20211130-230456](https://user-images.githubusercontent.com/117757/144073925-56b82efa-5488-48ed-b748-d7e65ca12e89.png) ![2](https://user-images.githubusercontent.com/117757/144073963-b81e03f2-5161-4cfe-8f6e-b5f7b8390e05.png)
> 
> 接口的权限管理功能应该是修改了，不再像文档和视频里说明的那样了
> 
> 1. 在sys_api表中手动插入所需的接口信息
> 2. 进入菜单管理，选中所需菜单或功能(分页获取、创建、修改这些) 点击操作栏的修改，在最下方的api权限中，将对应的接口授权到菜单或功能上
> 3. 进入角色管理界面，修改角色的菜单权限，选中提交后重新登录就可以使用了
> 
> 意思是将接口的权限放在菜单上进行处理，但数据库中还是绑定在角色上的 会导致一个问题，如果修改了一个菜单包含的接口权限，但是没有修改角色的菜单权限，角色所拥有的应该还是之前的权限，有待设计

在最下方的api权限中，将对应的接口授权到菜单或功能上 ----- 这个api权限在哪里呢

**Comment by kakrot-16** [comment]
我依然无法解决

**Comment by evacaptain** [comment]
1  ./go-admin server -c=config/settings.dev.yml -a=true 重新跑一下，然后在系统管理-接口管理-会出现新增的api，编辑一下
2  系统管理-菜单管理，找到报无权限的菜单，配置上刚才编辑的api
3  在系统管理-角色管理中，给无权限的角色勾选上菜单（无论之前此角色是否已经可以勾选菜单，都需要勾选，触发更新操作，这里算个bug吧）
4  如果还不行，尝试在菜单上重新授权api，把角色的菜单访问权限先勾掉，确定，再勾选上菜单，确定

**Comment by kpskylonely** [comment]
> 1 ./go-admin server -c=config/settings.dev.yml -a=true 重新跑一下，然后在系统管理-接口管理-会出现新增的api，编辑一下
> 2 系统管理-菜单管理，找到报无权限的菜单，配置上刚才编辑的api
> 3 在系统管理-角色管理中，给无权限的角色勾选上菜单（无论之前此角色是否已经可以勾选菜单，都需要勾选，触发更新操作，这里算个bug吧）
> 4 如果还不行，尝试在菜单上重新授权api，把角色的菜单访问权限先勾掉，确定，再勾选上菜单，确定

 ./go-admin server -c=config/settings.dev.yml -a=true 重新跑一下，接口管理里面没有新增的接口，请问这个问题怎么解决？

**Comment by evacaptain** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by evacaptain** [comment]
检查下脚本吧，是不是执行这段命令了，或者你本地运行，以这段命令启动，实在不行去看下sys-api的数据库，自己插一行记录




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年6月20日(星期一) 下午2:56
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [go-admin-team/go-admin] 对不起，您没有该接口访问权限，请联系管理员 (Issue #577)





  
1 ./go-admin server -c=config/settings.dev.yml -a=true 重新跑一下，然后在系统管理-接口管理-会出现新增的api，编辑一下
 2 系统管理-菜单管理，找到报无权限的菜单，配置上刚才编辑的api
 3 在系统管理-角色管理中，给无权限的角色勾选上菜单（无论之前此角色是否已经可以勾选菜单，都需要勾选，触发更新操作，这里算个bug吧）
 4 如果还不行，尝试在菜单上重新授权api，把角色的菜单访问权限先勾掉，确定，再勾选上菜单，确定
  
./go-admin server -c=config/settings.dev.yml -a=true 重新跑一下，接口管理里面没有新增的接口，请问这个问题怎么解决？

**Comment by wenjianzhang** [comment]
> 我依然无法解决

要看看当前使用的版本是否支持 -a 指令

**Comment by wenjianzhang** [comment]
> 检查下脚本吧，是不是执行这段命令了，或者你本地运行，以这段命令启动，实在不行去看下sys-api的数据库，自己插一行记录
> […](#)
> ------------------&nbsp;Original&nbsp;------------------ From: ***@***.***&gt;; Date: 2022年6月20日(星期一) 下午2:56 To: ***@***.***&gt;; Cc: ***@***.***&gt;; ***@***.***&gt;; Subject: Re: [go-admin-team/go-admin] 对不起，您没有该接口访问权限，请联系管理员 (Issue #577) 1 ./go-admin server -c=config/settings.dev.yml -a=true 重新跑一下，然后在系统管理-接口管理-会出现新增的api，编辑一下 2 系统管理-菜单管理，找到报无权限的菜单，配置上刚才编辑的api 3 在系统管理-角色管理中，给无权限的角色勾选上菜单（无论之前此角色是否已经可以勾选菜单，都需要勾选，触发更新操作，这里算个bug吧） 4 如果还不行，尝试在菜单上重新授权api，把角色的菜单访问权限先勾掉，确定，再勾选上菜单，确定 ./go-admin server -c=config/settings.dev.yml -a=true 重新跑一下，接口管理里面没有新增的接口，请问这个问题怎么解决？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

不建议手动添加api记录
