### ISSUE TITLE
自定义配置项如何设置

### ISSUE THREAD

**Issue by ACV-er** [go-admin-team/go-admin#579]
自定义配置项文档中并没区分大小写，驼峰命名应该如何定义，结构体名和属性名在config/extend.go和settings.yml里面分别如何对应？

**Comment by ACV-er** [comment]
我无法读取我的配置，我读取的内容是空

**Comment by wenjianzhang** [comment]
![image](https://user-images.githubusercontent.com/3890175/146327553-2b9df61b-c5bc-4ded-a40c-b3876729cb70.png)
