### ISSUE TITLE
各位大牛，有段Insert代码看不明白，能否帮忙解释一下呢？

### ISSUE THREAD

**Issue by nottellyou** [go-admin-team/go-admin#581]
func (e TProject) Insert(c *gin.Context) {
	req := dto.TProjectInsertReq{}
	s := service.TProject{}
	**err := e.MakeContext(c).
		MakeOrm().
		Bind(&req).
		MakeService(&s.Service).
		Errors**
	if err != nil {
		e.Logger.Error(err)
		e.Error(500, err, err.Error())
		return
	}
	// 设置创建人
	req.SetCreateBy(user.GetUserId(c))

	err = s.InsertBatch(&req)
	if err != nil {
		e.Error(500, err, fmt.Sprintf("创建项目基表  失败，\r\n失败信息 %s", err.Error()))
		return
	}

	e.OK(req.GetId(), "创建成功")
}
就是加粗的这一段代码。大概意思是绑定变量并解析，但为啥又用了一个MakeOrm()？

**Comment by wenjianzhang** [comment]
MakeOrm() 获取orm对象

**Comment by nottellyou** [comment]
多谢。
