### ISSUE TITLE
请问如何在这个框架下添加资源，让用户访问，比如一张照片，一个文档

### ISSUE THREAD

**Issue by zhangcy702** [go-admin-team/go-admin#583]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wenjianzhang** [comment]
做一个功能列表，上传资源，资源可以传到oss或者服务器本地，用户访问对应的地址就好了。。。

**Comment by zhangcy702** [comment]
好的，谢谢您



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月16日 15:32 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [go-admin-team/go-admin] 请问如何在这个框架下添加资源，让用户访问，比如一张照片，一个文档 (Issue #583) |

做一个功能列表，上传资源，资源可以传到oss或者服务器本地，用户访问对应的地址就好了。。。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
