### ISSUE TITLE
不加入搜索条件的情况下 分页失效

### ISSUE THREAD

**Issue by zengchengjie** [go-admin-team/go-admin#587]
**问题描述**
不加入搜索条件的情况下 分页失效，前端传递分页参数，接口返回分页的默认值：pageIndex 1 ，pageSize 10
当我加入一个任意一个搜索条件时，分页参数生效。

如代码所示
有问题的情况：
````
dto.Pagination `search:"-"`
TestOrder
````
修改后-增加一个查询参数（分页参数生效）：
````
dto.Pagination `search:"-"`
Name           string `form:"name"  search:"type:contains;column:name;table:test" comment:"测试"`
TestOrder
````
**使用版本**
github.com/go-admin-team/go-admin-core v1.3.8
github.com/go-admin-team/go-admin-core/sdk v1.3.8

**Comment by wenjianzhang** [comment]
![image](https://user-images.githubusercontent.com/3890175/148159943-ad2e16a2-85a0-42c6-b356-608809b68cd0.png)

这里是url传值哦

**Comment by zengchengjie** [comment]
不太明白您的意思，这种string `form:"name" 的方式我也能够进行URL查询。同时，怎么解释
`dto.Pagination `search:"-"`
TestOrder`
这种情况下分页查询失效呢，我是通过

**Comment by zengchengjie** [comment]
抱歉不太明白您的意思，我通过 `string `form:"name"`方式也能够进行URL传值搜索。
同时，该如何解释这种情况下分页失效的问题呢：
`dto.Pagination `search:"-"`
TestOrder`
这种情况下，分页搜索条件无法生效
http://host:port/api/v1/test?pageIndex=1&pageSize=1

**Comment by igo9go** [comment]
不加入搜索条件的情况下    分页就没法解析啊

**Comment by zengchengjie** [comment]
> 

那如果我的查询接口，没有别的查询条件，只有分页查询参数，就没法生效了吗？

**Comment by wenjianzhang** [comment]
> 抱歉不太明白您的意思，我通过 string `form:"name" 方式也能够进行URL传值搜索。 同时，该如何解释这种情况下分页失效的问题呢：
> 
> ```
> dto.Pagination `search:"-"`
> TestOrder
> ```
> 
> 这种情况下，分页搜索条件无法生效 http://host:port/api/v1/test?pageIndex=1&pageSize=1

使用场景是除了分页没有别的条件是吗？

**Comment by wenjianzhang** [comment]
需要将分页条件上提一层
