### ISSUE TITLE
初始化的迁移错误This table type requires a primary key

### ISSUE THREAD

**Issue by ACV-er** [go-admin-team/go-admin#590]
我在进行项目初始化的数据库迁移步骤时新建sys_casbin_rule时抛出This table type requires a primary key。我不想更改数据库设置，我尝试在cmd\migrate\migration\models\casbin_rule.go中加入一个主键Id，但是并没有生效。然后来我发现控制字段的地方在一个依赖包github.com\go-admin-team\go-admin-core\sdk@v1.3.9\pkg\casbin\mycasbin.go中。原则上我不应该去控制这个文件。我有什么办法解决这个问题？

**Comment by wenjianzhang** [comment]
这个问题目前可以设置索引的长度，后续go-admin会升级引用依赖来解决这个问题
