### ISSUE TITLE
config文件夹下找不到settings.dev.yml

### ISSUE THREAD

**Issue by memory125** [go-admin-team/go-admin#596]
在[官网文档](https://doc.go-admin.dev/)的上手文档中：
```
# 初始化数据库
# macOS or linux 下使用
$ ./go-admin migrate -c=config/settings.dev.yml
# ⚠️注意:windows 下使用
$ go-admin.exe migrate -c=config/settings.dev.yml
```
可是在源码`config`中只能找到`settings.full.yml`, `settings.sqlite.yml`和`settings.yml`，没有找到数据库初始化的`setting.dev.yml`文件。

- 是否需要将上述三个文件中的`sqlite`修改之，但是这样可能引发mysql跟sqlite配置的出入？

**Comment by wenjianzhang** [comment]
`setting.dev.yml`需要根据自己的环境进行配置的；
