### ISSUE TITLE
各位高手，问下权限校验的代码为 middleware.AuthCheckRole()，但它在哪里取数据库了呢？

### ISSUE THREAD

**Issue by nottellyou** [go-admin-team/go-admin#607]
各位高手，问下权限校验的代码为 middleware.AuthCheckRole()，但它在哪里取数据库了呢？

现在我新建了一个角色，然后登录时，部分新增的接口报403无权限。所以想看看权限是在哪里取数据库了？

**Comment by wenjianzhang** [comment]
可以查看中间件，或者 查看 `casbin`相关文档
