### ISSUE TITLE
请问：怎样将login_log和opera_log的日志入库呢？

### ISSUE THREAD

**Issue by nottellyou** [go-admin-team/go-admin#608]
请问：怎样将login_log和opera_log的日志入库呢？

现在登录后，看不到登录日志，怎样将日志入库呢？目前来看好像是日志进入了队列，但没有发现什么地方消耗这些队列中的日志了。

**Comment by jy0449** [comment]
在配置settings.yml，把 logger 的 enableddb改成true，就有登录日志和操作日志了。

**Comment by nottellyou** [comment]
多谢，已经有日志入库了。
