### ISSUE TITLE
5次查看演示地址，4次进不去，可否把修改密码功能禁用？

### ISSUE THREAD

**Issue by sage-z** [go-admin-team/go-admin#613]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wenjianzhang** [comment]
有人把账号停用了。遇到这个问题，可以添加微信群，及时告知，谢谢！
