### ISSUE TITLE
数据库生成过程中间发生错误

### ISSUE THREAD

**Issue by aion1998** [go-admin-team/go-admin#620]
**Describe the bug**

### 错误输出如下：

![image](https://user-images.githubusercontent.com/19725014/159132789-1854caf1-5654-404c-8cbe-5c5247766359.png)

**To Reproduce**

 - Version lates

- Windows 10 系统
- IDE是 VSCode

**Comment by wenjianzhang** [comment]
这个需要自行处理掉mysql配置相关问题，可以百度 `mysql 1071`
