### ISSUE TITLE
关于api表在使用生成代码无新增接口的问题解决

### ISSUE THREAD

**Issue by LiuxzDrew** [go-admin-team/go-admin#623]
我在使用v2.0.9 版本的生成代码后服务重启之后新增加的功能模块的路由接口不会在api表中增加，导致后期权限授权无法使用问题。

该问题解决是在服务启动的时候 go-admin server -c=config/settings.yml **-a=true**  增加**-a=true**  参数解决。该参数是在服务启动时把路由接口插入到api 表中。

作者在空闲时间在文档教程的中编写第一个项目部分写上这个，感谢。

**Comment by wenjianzhang** [comment]
收到
