### ISSUE TITLE
菜单管理设置导致前端找不到views目录

### ISSUE THREAD

**Issue by iakirago** [go-admin-team/go-admin#626]
1、导入数据库，为表news设置生成代码，会把生成的表挂在“主目录下”
2、在菜单管理里，创建一个目录”内容管理“，路由名称、组件路径、路由地址均为空，外链为 否，菜单状态设置为显示，保存
3、在菜单管理里，修改news下级news（带权限标识和组件路径的），修改其上级菜单为步骤2创建的 “内容管理”，其他内容不变，保存
4、在 “内容管理”目录访问news，页面进度条一直加载，无内容显示
5、查看页面控制台，提示如下
`
app.js:978 
        
       Error: Cannot find module './views'
    at webpackContextResolve (eval at ./src sync recursive ^\.\/views.*$ (0.js:8329:1), <anonymous>:180:11)
    at webpackContext (eval at ./src sync recursive ^\.\/views.*$ (0.js:8329:1), <anonymous>:175:11)
    at eval (permission.js?31c2:58:1)
`

不知道是我设置的问题，还是是个bug？
希望在“代码生成”添加选项“是生成目录还是菜单”，并提供选择上级菜单关联

**Comment by logtous** [comment]
go-admin和go-admin-ui是否在同一级目录下？

**Comment by iakirago** [comment]
> go-admin和go-admin-ui是否在同一级目录下？

在同一级目录下，按照文档提示，我创建了myproject目录，然后分别clone了前后端新项目

**Comment by wenjianzhang** [comment]
> 

默认是生成同go-admin同级目录的go-admin-ui文件夹中，菜单数据可以使用也是可以一键生成的，不需要手动创建，如果手动创建，请检查相关数据是否正确，反馈的这个问题目前使用当中是不存在的；
反馈的需求我们会认真考虑。
谢谢！
