### ISSUE TITLE
快出vue3版本吧，前端太丑了，建议前端参考 ruoyi 

### ISSUE THREAD

**Issue by ssuhvs** [go-admin-team/go-admin#636]
快出vue3版本吧，建议前端参考 ruoyi

**Comment by wenjianzhang** [comment]
这个建议会考虑的。如果觉得go-admin对你有帮助请一键三连，防止以后找不到了。

**Comment by atomanV** [comment]
https://vue3.go-admin.dev/ 是不是不可用？

**Comment by atomanV** [comment]
有计划什么时候release vue3的版本吗？如果release，用你们现在的vue2，可以直接升级吗？
