### ISSUE TITLE
定时任务-日志存在程序自动退出

### ISSUE THREAD

**Issue by xz-zone** [go-admin-team/go-admin#637]
进入定时任务-日志
![image](https://user-images.githubusercontent.com/19305748/163328568-48bab453-3767-4a6b-a508-c2ba80dc21cc.png)
程序自动退出
![image](https://user-images.githubusercontent.com/19305748/163328677-9f58ff53-cc95-4382-8b6a-8136fa642c68.png)

**Comment by wenjianzhang** [comment]
项目中这个功能暂时没有正式开放。可以先通过文件日志打印

**Comment by xz-zone** [comment]
但是文件并没有写入日志。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "go-admin-team/go-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月15日(星期五) 上午10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [go-admin-team/go-admin] 定时任务-日志存在程序自动退出 (Issue #637)





 
项目中这个功能暂时没有正式开放。可以先通过文件日志打印
