### ISSUE TITLE
定时任务页面存在交互问题

### ISSUE THREAD

**Issue by hellopyj** [go-admin-team/go-admin#638]
**Describe the bug**
1.定时任务状态关闭也可以启动执行
2.定时任务日志点击空白

**Comment by wenjianzhang** [comment]
> 

能否详细描述您的问题，我们好定位并修复这个问题。

**Comment by wenjianzhang** [comment]
问题2:日志部分目前还没开发完成，后续会先将按钮移除，功能完成后开发出来，当前日志可在控制台中查看。
