### ISSUE TITLE
gin.Context泄漏

### ISSUE THREAD

**Issue by evacaptain** [go-admin-team/go-admin#645]
MakeContext时，会把gin.Context赋值给*xxxxSerivice的一个成员变量，并发情况下会panic，报错http: wrote more than the declared Content-Length

**Comment by evacaptain** [comment]
不应该在router里把api对象设为全局的，修改这里就好了

**Comment by wenjianzhang** [comment]
这个问题我们进行了压力测试并没有出现？
或者提供一下详细代码，我们也很乐意解决这样的问题。

**Comment by evacaptain** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by evacaptain** [comment]
在我的问题情境中，是其它服务向go-admin发送http请求，异常记录显示在api返回时报错，例如e.OK(data,"success")，你可以模拟下试试；我在router里不再通过api对象传入handlerFunc而是改用包名调用，这个问题就没有再出现了



------------------&nbsp;Original&nbsp;------------------
From: "wenjianzhang"; 
Date: Friday, May 27, 2022 11:14 PM
To: "go-admin-team/go-admin"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [go-admin-team/go-admin] gin.Context泄漏 (Issue #645)





 
这个问题我们进行了压力测试并没有出现？
 或者提供一下详细代码，我们也很乐意解决这样的问题。

**Comment by wenjianzhang** [comment]
使用的是那个版本？

<img width="414" alt="image" src="https://user-images.githubusercontent.com/3890175/170736597-96f5b777-df0c-4efa-bf7a-73fb0ab9ce25.png">
定义接口时：
正确：`func (e SysApi) Get`
错误: `func (e *SysApi) Get`

**Comment by evacaptain** [comment]
我用的指针，可能是这里的原因？我没有深入看源码



------------------&nbsp;Original&nbsp;------------------
From: "wenjianzhang"; 
Date: Saturday, May 28, 2022 0:04 AM
To: "go-admin-team/go-admin"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [go-admin-team/go-admin] gin.Context泄漏 (Issue #645)





 
使用的是那个版本？
 

 定义接口时： 正确：`func (e SysApi) Get` 错误: `func (e *SysApi) Get`

**Comment by wenjianzhang** [comment]
done
