### ISSUE TITLE
文档表述错误

### ISSUE THREAD

**Issue by jiajie99** [go-admin-team/go-admin#648]
本人按照文档命令启动
![1653470227(1)](https://user-images.githubusercontent.com/56350560/170227931-d031226f-df04-465c-b706-a5df597483ba.png)
出现错误
`2022/05/25 17:11:51 Load config source fail: error loading source file: open config\settings: The system cannot find the file specifie
d.`
后使用
`.\go-admin server -c .\config\settings.dev.yml`
启动成功
建议作者及时更改文档表述

**Comment by jiajie99** [comment]
windows环境

**Comment by jiajie99** [comment]
对的，多了个“=”号

**Comment by wenjianzhang** [comment]
ok
