### ISSUE TITLE
vue写的UI大卡了

### ISSUE THREAD

**Issue by auqf** [go-admin-team/go-admin#653]
UI效果大水了

**Comment by fengdoudm** [comment]
@auqf 兄台，有问题说问题，你有能耐自己改进或贡献代码，别喷，没人求你用。

**Comment by wenjianzhang** [comment]
> UI效果大水了

或者您有什么建议行的pr可以提交；

另外UI不在这里提交Issues，可以到 https://github.com/go-admin-team/go-admin-ui/issues 反馈
