### ISSUE TITLE
编译项目失败，提示需要输入github.com 的用户名和密码

### ISSUE THREAD

**Issue by q629988171** [go-admin-team/go-admin#657]
# 环境说明

1. go version go1.16.13 linux/amd64
2. centos 7.9
3. [go-admin 4925383f5e9ddc627490334dc146e7c204960281](https://github.com/go-admin-team/go-admin/commit/4925383f5e9ddc627490334dc146e7c204960281)
4. Docker version 20.10.14, build a224086

# 问题描述
编译项目失败，提示需要输入github.com 的用户名和密码

# 复现过程
1. 创建开发目录
mkdir goadmin
cd goadmin

2. 获取后端代码
git clone https://github.com/go-admin-team/go-admin.git

3. 获取前端代码
git clone https://github.com/go-admin-team/go-admin-ui.git

5. 进入 go-admin 后端项目
cd ./go-admin

6. 编译项目
go build

提示需要：go mod download github.com/alecthomas/template
回车之后：Username for 'https://github.com'， Password for 'https://github.com'

这是因为哪个依赖转为私有的原因吗？

**Comment by wenjianzhang** [comment]
这个问题并没有重现，可以参照[go-admin 文档](https://doc.go-admin.dev/guide/ksks) 在次确认一下；

另外我们也查看了 github.com/alecthomas/template 这个项目并没有私有化；

**Comment by q629988171** [comment]
> 这个问题并没有重现，可以参照[go-admin 文档](https://doc.go-admin.dev/guide/ksks) 在次确认一下；
> 
> 另外我们也查看了 github.com/alecthomas/template 这个项目并没有私有化；

## Windows 环境

Windows 10 x64 [版本 10.0.17763.2928]

go version go1.16.5 windows/amd64

go-admin-2.0.11

参照 [go-admin 文档](https://doc.go-admin.dev/guide/ksks) 编译成功。



## Linux 环境

centos 7.9

go version go1.17.7 linux/amd64

go-admin-2.0.11

参照 [go-admin 文档](https://doc.go-admin.dev/guide/ksks) 编译成功。
