### ISSUE TITLE
初始化数据库或者启动均报错panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by htyypt** [go-admin-team/go-admin#658]
我clone使用最新版本，配置文件使用sqlite3数据库，在初始化数据时报错：

是否要提前建立好一个空库？我试过在根目录和config目录，似乎都没用。谢谢！

![image](https://user-images.githubusercontent.com/81215528/172792399-343adca8-07da-45cb-b48c-7077dffa7a26.png)

**Comment by q629988171** [comment]
> 我clone使用最新版本，配置文件使用sqlite3数据库，在初始化数据时报错：
> 
> 是否要提前建立好一个空库？我试过在根目录和config目录，似乎都没用。谢谢！
> 
> ![image](https://user-images.githubusercontent.com/81215528/172792399-343adca8-07da-45cb-b48c-7077dffa7a26.png)

我用的是mysql 数据库，初始化数据成功。建议你试试。

**Comment by wenjianzhang** [comment]
sqlite类型数据库，可以创建一个新的数据文件，修改配置，然后再做数据初始化；

**Comment by gongcf** [comment]
先编译出执行文件
CGO_ENABLED=1 go build -tags sqlite3 -ldflags="-w -s" -a -installsuffix -o go-admin .
然后
./go-admin migrate -c config/settings.sqlite.yml

**Comment by xiliangMa** [comment]
@gongcf 感谢sqlite初始化失败问题已经解决
