### ISSUE TITLE
执行go mod tidy时错误

### ISSUE THREAD

**Issue by svenjia** [go-admin-team/go-admin#659]
![image](https://user-images.githubusercontent.com/29444841/172981221-d2a0643b-e707-415c-9883-c9d9659889ab.png)

**Comment by svenjia** [comment]
目前按照文档上的这一步，跑不通
![image](https://user-images.githubusercontent.com/29444841/172986390-d3425106-fd43-45b4-9536-5116c3a2b10b.png)

**Comment by Creator1024** [comment]
依赖的依赖库被删了..

**Comment by svenjia** [comment]
> 依赖的依赖库被删了..

执行build命令的时候，又提示很多文件没有go.sum入口
![image](https://user-images.githubusercontent.com/29444841/173005430-87cd8f04-3612-4eae-9008-6a9f88da77a1.png)

**Comment by wenjianzhang** [comment]
建议尝试单独下载或者是用go get 独立安装；这些库并没有删除；

或者检查 配置使用goproxy

**Comment by svenjia** [comment]
> 

嗯，我重新配置goproxy后，重新拉项目，目前流程是跑通了，谢谢
