### ISSUE TITLE
代码生成接口失败

### ISSUE THREAD

**Issue by q629988171** [go-admin-team/go-admin#660]
**Describe the bug**
代码生成接口失败

**To Reproduce**
1. 创建数据库表信息
2. 将表结构导入系统
3. 对导入数据进行编辑
4. 代码生成
5. 生成配置

**Expected behavior**
参考 [go-admin应用2](https://doc.go-admin.dev/intro/tutorial02#%E7%BC%96%E5%86%99-go-admin-%E5%BA%94%E7%94%A8%E7%AC%AC-2-%E6%AD%A5) 生成代码，当我打开 '内容管理' 却显示 404，添加内容也显示失败。

go-admin server -c config\settings.dev.yml -a true 也没有生成 ` article `  接口信息

打开 `sys_api` 表，没有找到 ` article `  接口信息。

我已经在 `centos` 和 windows 10 环境中测试，也在多个 `go-admin` 和 `go-admin-ui` 测试，都失败。

**Screenshots**

![字段信息](https://user-images.githubusercontent.com/2260447/173074241-ac147c18-c8e9-4212-ac06-85f1146566db.jpg)

![代码生成](https://user-images.githubusercontent.com/2260447/173074331-eec6de7c-c5dd-435c-8e60-7700dff5e3e3.jpg)

![文章404](https://user-images.githubusercontent.com/2260447/173074419-f40064e6-d264-4f7b-acf0-78d18a742a1b.jpg)

![数据中没有接口信息](https://user-images.githubusercontent.com/2260447/173074463-ba63ea57-bfc7-4980-a7cd-90584ac19656.jpg)

**Desktop (please complete the following information):**

 - OS: Windows 10 x64 [版本 10.0.17763.2928]
 - Chrome 版本 102.0.5005.63（正式版本） （64 位）
 - go1.16.5.windows-amd64
 - go-admin-2.0.9
 - go-admin-ui-2.0.9
 - mysql-installer-community-8.0.29.0
 - node v14.16.0
 - npm 6.14.11

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wenjianzhang** [comment]
服务端代码生成完需要重新编译程序，并重新启动；

**Comment by wenjianzhang** [comment]
建议看看：https://doc.go-admin.dev/
