### ISSUE TITLE
每次编写完接口后要编译重启吗？怎么调试呢。

### ISSUE THREAD

**Issue by guipie** [go-admin-team/go-admin#667]
![doc zhangwj com_intro_tutorial01](https://user-images.githubusercontent.com/55727172/176997442-f897ea62-f86e-47e4-a9a4-346e166afd06.png)

**Comment by wenjianzhang** [comment]
需要编译的，可以使用goland来调试

**Comment by wenjianzhang** [comment]
需要编译的，可以使用goland来调试
