### ISSUE TITLE
token 续签问题

### ISSUE THREAD

**Issue by dongliangde** [go-admin-team/go-admin#672]
**token 续签问题**
生成的token如果过期时间太短，则每次到期后，都需要用户重新登录,生成的token如果过期时间太长，由于token签发后，在有效期内无法注销，存在安全隐患.一般token过期后，后台都会返回一个新的token 。建议加个续签token的机制

**Comment by dongliangde** [comment]
请教大家一下：目前大部分的解决方式，通过redis来解决，除了redis还有其他的解决方案吗？欢迎大家评价

**Comment by wenjianzhang** [comment]
也可以缩短有效期，刷新token

**Comment by sunny086** [comment]
jwtauth有一个最大刷新时间；或者你们自己前后端配合做一个token续签，后端接口有请求来就判断时间，满足就给header一个newtoken，前端全局拦截中拿到这个token进行替换也可以实现

**Comment by dongliangde** [comment]
> jwtauth有一个最大刷新时间；或者你们自己前后端配合做一个token续签，后端接口有请求来就判断时间，满足就给header一个newtoken，前端全局拦截中拿到这个token进行替换也可以实现

好的,谢谢建议
