### ISSUE TITLE
可以初始化表的时候设置utf8，适配数据库不是utf8的人

### ISSUE THREAD

**Issue by Vingurzhou** [go-admin-team/go-admin#674]
1. Go to './cmd/migrate/migration/version/1599190683659_tables.go'
2. Scroll down to '1599190683659_tables.go:20'
3. err := tx.Set("gorm:table_options", "ENGINE=InnoDB DEFAULT CHARSET=utf8").Debug().Migrator().AutoMigrate(
			new(models.CasbinRule),
			new(models.SysDept),
			new(models.SysConfig),
			new(models.SysTables),
			new(models.SysColumns),
			new(models.SysMenu),
			new(models.SysLoginLog),
			new(models.SysOperaLog),
			new(models.SysRoleDept),
			new(models.SysUser),
			new(models.SysRole),
			new(models.SysPost),
			new(models.DictData),
			new(models.DictType),
			new(models.SysJob),
			new(models.SysConfig),
			new(models.SysApi),
			new(models.TbDemo),
		)

**Comment by wenjianzhang** [comment]
可以提交pr哦
