### ISSUE TITLE
/api/v1/login 登录接口错误响应，导致内存溢出

### ISSUE THREAD

**Issue by zhoujialefanjiayuan** [go-admin-team/go-admin#683]
```
func (mw *MyLogin) Unauthorized(c *gin.Context, code int, message string) {
	c.Header("WWW-Authenticate", "JWT realm="+mw.Realm)
	if !mw.DisabledAbort {
		c.Abort()
	}
	mw.Unauthorized(c, code, message)
}
```

这段代码，登录错误响应陷入死循环

**Comment by zhoujialefanjiayuan** [comment]
### 问题发生
今天服务日志显示内存溢出，服务直接打死，查看原因是登录接口错误响应时，陷入死循环。

### 解决
若开发者无自定义错误响应，jwtauth包有内置函数，建议直接注释框架内生成代码 func (mw *MyLogin) Unauthorized(c *gin.Context, code int, message string)

```
#  jwtauth包有内置函数
if mw.Unauthorized == nil {
		mw.Unauthorized = func(c *gin.Context, code int, message string) {
			c.JSON(http.StatusOK, gin.H{
				"code":    code,
				"message": message,
			})
		}
	}
```

**Comment by wenjianzhang** [comment]
> ```
> func (mw *MyLogin) Unauthorized(c *gin.Context, code int, message string) {
> 	c.Header("WWW-Authenticate", "JWT realm="+mw.Realm)
> 	if !mw.DisabledAbort {
> 		c.Abort()
> 	}
> 	mw.Unauthorized(c, code, message)
> }
> ```
> 
> 这段代码，登录错误响应陷入死循环

这段代码不是go-admin的代码吧？

**Comment by ahKevinXy** [comment]
以前老代码吧,我之前用最早版本也是那样的
