### ISSUE TITLE
拉去最新版本的代码 运行 ./go-admin.exe migrate -c config/settings.dev.yml报错

### ISSUE THREAD

**Issue by leiweihao** [go-admin-team/go-admin#684]
![1660213188320](https://user-images.githubusercontent.com/57650467/184113186-c817f9da-d454-4f50-8335-4ccb78e36c6b.jpg)

**Comment by leiweihao** [comment]
已解决

**Comment by aohanhongzhi** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/37319319/208303479-2d9687ed-1d3e-4835-b1b9-a9ab7c2713ac.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/37319319/208303732-884bc81e-f8ca-4be6-baf0-edd937de272a.png">
