### ISSUE TITLE
如何修改侧边栏菜单排序

### ISSUE THREAD

**Issue by safe6Sec** [go-admin-team/go-admin#690]
![image](https://user-images.githubusercontent.com/26316334/184823655-1dbfe3cb-1667-421f-a0f5-1f537b8011c4.png)
我想把自己创建的模块放最前面

**Comment by wenjianzhang** [comment]
修改菜单排序字段即可，正序排列

**Comment by wenjianzhang** [comment]
https://github.com/go-admin-team/go-admin/commit/90db381b5afb6e0247f3cfc7b27992412dcd15e8

**Comment by wenjianzhang** [comment]
已修复
