### ISSUE TITLE
添加角色,勾选代码生成配置的菜单列表,提交时报错创建失败,empty slice found

### ISSUE THREAD

**Issue by JaydenForYou** [go-admin-team/go-admin#691]
添加角色,勾选代码生成配置的菜单列表,提交时报错创建失败,empty slice found
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/53374430/184944454-7c3d842e-712d-4875-9754-b0dc7070f243.png">

**Comment by wenjianzhang** [comment]
重复提交(#687)
