### ISSUE TITLE
初始化脚本缺失database goadmin 创建脚本

### ISSUE THREAD

**Issue by tonysprite** [go-admin-team/go-admin#704]
### Reproduction link

[https://github.com/tonysprite/go-admin](https://github.com/tonysprite/go-admin)

### Steps to reproduce

按照官方文档操作
go run main.go migrate -c config/settings.yml
报错
admin-core@v1.3.8/tools/database/config.go:39 [error] failed to initialize database, got error Error 1049: Unknown database 'goadmin'
2022-08-31 21:02:38.730 0800 file:database/initialize.go:56 level:fatal mysql connect error :Error 1049: Unknown database 'goadmin'
exit status 1

### What is expected?

go-admin项目migrate 的前置动作应该是创建数据库 

### What is actually happening?

Error 1049: Unknown database 'goadmin'
数据库不存在

| Environment | Info |
| --- | --- |
| go-admin | master |
| Go | go version go1.17.6 darwin/arm64 |
| System | mac |
| Browser | chrome |

---
1.修改官方migrate文档 增加数据库创建脚本
create database goadmin default character set utf8mb4 collate utf8mb4_bin;
2.migrate脚本支持自动实现1的动作

**Comment by wenjianzhang** [comment]
数据库还是需要自行创建一下的
