### ISSUE TITLE
新建角色的用户无法修改个人信息

### ISSUE THREAD

**Issue by Fav** [go-admin-team/go-admin#712]
**Describe the bug**
新建角色的用户无法修改个人信息

**To Reproduce**
1. 以管理员角色登录，创建用户角色，并创建一个用户，数据权限设置为【仅本人数据权限】，菜单权限不设置
2. 以用户角色登录，打开个人中心，修改昵称，手机号，密码等之后提交，提示无权限
3. 如果以管理员角色登录将用户角色的菜单权限设置为【系统管理】【用户管理】【允许修改管理员】，再以用户角色登录，这样虽然可以修改自己的信息，但是会出现一个【系统管理】【用户管理】的菜单，这里如果同时开放【允许查看管理员】,用户可以查看管理员的信息，这个不合理

**Desktop (please complete the following information):**
 - OS:win10
 - Browser edge,chrome
 - Version go-admin-2.0.12,go-admin-ui-2.0.9

**Comment by wenjianzhang** [comment]
请确认是否是相关菜单接口未绑定配置？

**Comment by itcbx** [comment]
也是同样的问题，非管理员账号，如果不添加管理权限，则无法修改密码和个人信息，但是如果增加了菜单权限，则会显示用户管理的菜单，这个是不对的，明明有问题，为什么要关闭这个issue
