### ISSUE TITLE
偶发接口报错： http: wrote more than the declared Content-Length问题

### ISSUE THREAD

**Issue by shengyun1992** [go-admin-team/go-admin#738]
请求接口会偶发 http: wrote more than the declared Content-Length

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/111720527/224591774-9963e6eb-d31c-4e67-9f8c-ba1df827a7c6.png">

我的接口如下：
<img width="963" alt="image" src="https://user-images.githubusercontent.com/111720527/224591891-192b3901-1239-48e7-bc5d-7a88f9e1a3b9.png">

**Comment by wenjianzhang** [comment]
截图里看不到行号，错误信息里可以看到是474
行

**Comment by wenjianzhang** [comment]
e *XXX 的*去掉

**Comment by shengyun1992** [comment]
改成(e ChannelTask) 是吗
