### ISSUE TITLE
代码生成之后访问 404

### ISSUE THREAD

**Issue by D3ngX1n** [go-admin-team/go-admin#763]
代码生成之后，系统存在前端页面，文件夹代码也存在 但访问出现
Request failed with status code 404

**Comment by wenjianzhang** [comment]
代码生成以后404，是因为后端需要重新编译再启动，生成的代码是不会编译到运行中的二进制文件的

**Comment by Chriscookie** [comment]
> 代码生成以后404，是因为后端需要重新编译再启动，生成的代码是不会编译到运行中的二进制文件的

**Comment by Chriscookie** [comment]
你好大佬，我是启动前端项目404我看接口请求的是前端的端口 ‘9527’ ，这是为什么

> 代码生成以后404，是因为后端需要重新编译再启动，生成的代码是不会编译到运行中的二进制文件的

**Comment by wenjianzhang** [comment]
生成以后需要重新编译项目
否则是访问不到的
