### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by liaokylin** [go-admin-team/go-admin#775]
when i run go build then some message show like this:

cannot use &Logger{} (value of type *Logger) as "github.com/casbin/casbin/v2/log".Logger value in argument 
to log.SetLogger: *Logger does not implement "github.com/casbin/casbin/v2/log".Logger (missing method LogError)

**Comment by sturn** [comment]
+1

**Comment by hong-0220** [comment]
+1

**Comment by hong-0220** [comment]
> 当我运行 go build 时，会显示一些消息，如下所示：
> 
> 无法将 &Logger{}（*Logger 类型的值）用作“github.com/casbin/casbin/v2/log”。参数中的 Logger 值 to log.SetLogger: *Logger 未实现“github.com/casbin/casbin/v2/log”.Logger（缺少方法 LogErr

> 当我运行 go build 时，会显示一些消息，如下所示：
> 
> 无法将 &Logger{}（*Logger 类型的值）用作“github.com/casbin/casbin/v2/log”。参数中的 Logger 值 to log.SetLogger: *Logger 未实现“github.com/casbin/casbin/v2/log”.Logger（缺少方法 LogError）



> +1

你有解决吗

**Comment by hong-0220** [comment]
> +1

你有解决吗

**Comment by msszzj** [comment]
go get github.com/casbin/casbin/v2@v2.54.0

**Comment by wenjianzhang** [comment]
请使用系统对应的package版本
