### ISSUE TITLE
你好，使用生成配置后使用接口会报错。

### ISSUE THREAD

**Issue by xianlv1996** [go-admin-team/go-admin#783]
![image](https://github.com/go-admin-team/go-admin/assets/151804438/e54f4faa-ebb6-4550-9c50-d06e530a08bb)
Uncaught (in promise) Error: Request failed with status code 404
    at createError (createError.js?2d83:16:1)
    at settle (settle.js?467f:17:1)
    at XMLHttpRequest.handleLoad (xhr.js?b50d:62:1)

路由代码中提示方法异常：
![image](https://github.com/go-admin-team/go-admin/assets/151804438/6850e3a3-ed8d-49de-a3bc-5824df1cc437)

**Comment by xianlv1996** [comment]
PS D:\Go\gocode\go-admin> go build
# go-admin/app/admin/router
app\admin\router\acticle.go:19:29: api.GetArticleList undefined (type apis.Article has no field or method GetArticleList)
PS D:\Go\gocode\go-admin>

**Comment by wenjianzhang** [comment]
<img width="441" alt="image" src="https://github.com/go-admin-team/go-admin/assets/3890175/1e38c8dd-1b33-406a-b398-30cf994b890a">
确认一下这个文件中是否存在这个接口
