### ISSUE TITLE
安装官网，编写第一个go-admin应用和第二个，全部步骤完成后报错了

### ISSUE THREAD

**Issue by xianlv1996** [go-admin-team/go-admin#784]
![image](https://github.com/go-admin-team/go-admin/assets/151804438/b28daa8a-0a15-4bff-9c23-a18cb0508371)
createError.js?2d83:16 Uncaught (in promise) Error: Request failed with status code 404
    at createError (createError.js?2d83:16:1)
    at settle (settle.js?467f:17:1)
    at XMLHttpRequest.handleLoad (xhr.js?b50d:62:1)

**Comment by xianlv1996** [comment]
.\go-admin.exe version
2.1.2

**Comment by wenjianzhang** [comment]
后端添加好api以后是需要重新build 后再启动的。
