### ISSUE TITLE
这框架前端写的可以 后端真是火葬场 方法该来该去乱的一笔 构建三分钟 改一个功能要三天 恶心的一笔

### ISSUE THREAD

**Issue by QTTQ** [go-admin-team/go-admin#785]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 2015WUJI01** [comment]
前端 bug 也不少，还有 icon 错乱的 bug

**Comment by whileW** [comment]
api部分
如果
func (e SysApi) GetPage(c *gin.Context) 不小心加了一个* 变成 func (e *SysApi) GetPage(c *gin.Context)

**Comment by 2015WUJI01** [comment]
> api部分
> 
> 如果
> 
> func (e SysApi) GetPage(c *gin.Context) 不小心加了一个* 变成 func (e *SysApi) GetPage(c *gin.Context)
> 
> 内部 MakeContext(c) 可能会导致并发问题，b请求的context会覆盖掉a请求的context

你这么一说还真是，平常没考虑这个问题

**Comment by baowk** [comment]
后端还有内存泄漏，太恐怖了

**Comment by lwnmengjing** [comment]
> > api部分
> > 如果
> > func (e SysApi) GetPage(c _gin.Context) 不小心加了一个_ 变成 func (e *SysApi) GetPage(c *gin.Context)
> > 内部 MakeContext(c) 可能会导致并发问题，b请求的context会覆盖掉a请求的context
> 
> 你这么一说还真是，平常没考虑这个问题

所以并发高的话，要慎重用

**Comment by wenjianzhang** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

抱歉go-admin对您造成了困扰，如果有具体的建议也可以提交过来的哦，一起为开源努力！
