### ISSUE TITLE
使用纯go实现的sqlite

### ISSUE THREAD

**Issue by guquan-lengyue** [go-admin-team/go-admin#789]
在[gorm官方文档中](https://gorm.io/zh_CN/docs/connecting_to_the_database.html#SQLite)有描述使用go实现的sqlite的使用方式
```go
import (
  "gorm.io/driver/sqlite" // Sqlite driver based on CGO
  // "github.com/glebarez/sqlite" // Pure go SQLite driver, checkout https://github.com/glebarez/sqlite for details
  "gorm.io/gorm"
)

// github.com/mattn/go-sqlite3
db, err := gorm.Open(sqlite.Open("gorm.db"), &gorm.Config{})
```

**Comment by lwnmengjing** [comment]
gorm.io/driver/sqlite还是依赖的github.com/mattn/go-sqlite3，一样需要cgo

**Comment by guquan-lengyue** [comment]
> ```go
> github.com/glebarez/sqlite
> ```



> gorm.io/driver/sqlite还是依赖的github.com/mattn/go-sqlite3，一样需要cgo
应该是我没有表达清楚。
官方文档有写可以使用的无cgo的sqlite依赖应该是`github.com/glebarez/sqlite`

**Comment by guquan-lengyue** [comment]
应该是我没有表达清楚。
官方文档有写可以使用的无cgo的sqlite依赖应该是`github.com/glebarez/sqlite`

**Comment by lwnmengjing** [comment]
> 应该是我没有表达清楚。 官方文档有写可以使用的无cgo的sqlite依赖应该是`github.com/glebarez/sqlite`

了解了，[mss-boot](https://github.com/mss-boot-io/mss-boot)会考虑引入

**Comment by lwnmengjing** [comment]
> 应该是我没有表达清楚。 官方文档有写可以使用的无cgo的sqlite依赖应该是`github.com/glebarez/sqlite`

这个库比较容易锁文件，感觉还不成熟
