### ISSUE TITLE
demo都无法登陆了！还有人在吗？

### ISSUE THREAD

**Issue by chaseSpace** [go-admin-team/go-admin#818]
Element UI vue demo：[https://vue2.go-admin.dev](https://vue2.go-admin.dev/#/login)

账号 / 密码： admin / 123456

Arco Design vue3 demo：[https://vue3.go-admin.dev](https://vue3.go-admin.dev/#/login)

账号 / 密码： admin / 123456

antd demo：https://antd.go-admin.pro/

账号 / 密码： admin / 123456

**Comment by Tiper-In-Github** [comment]
前段时间服务器到期后没有及时续费而已，目前已经恢复，请关闭该issue

**Comment by Tiper-In-Github** [comment]
> 又打不开了 [@Tiper-In-Github](https://github.com/Tiper-In-Github)

可能有些波动或当时正在维护，如果你截止现在还无法访问可参考：
https://github.com/go-admin-team/go-admin/discussions/830
